language: java
jdk:
- openjdk8

branches:
  only:
  - master
  - development

before_install:
  # - echo "$TNO_DOCKER_PASSWORD" | docker login app-docker136.hex.tno.nl -u "$TNO_DOCKER_USERNAME" --password-stdin
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  # the following pull commands are required because gradle docker task behaviour
  # are not supporting multible image builds within one project
  # - docker pull app-docker136.hex.tno.nl/vtmak/lrc:4.5f-alpine
  # - docker pull app-docker136.hex.tno.nl/pitch/lrc:5.4.3.0-alpine-nolib
  # - docker pull app-docker136.hex.tno.nl/portico/lrc:nightly-20160528-alpine

install: gradle install dockerBuildImage

script:
- export VERSION=$(grep "designatorVersion" ./.shared/libraries.gradle | awk '{print $3}' | tr -d \')
# tag and push test suite image
- docker tag ivct/ts-designator:$VERSION ivct/ts-designator:$TRAVIS_BRANCH-latest
- docker push ivct/ts-designator
# tag and push all rti specfic testapp images (Pitch, Mak, Portico)
- docker tag ivct/testapp:pi-skeleton-$VERSION ivct/testapp:pi-skeleton-$TRAVIS_BRANCH-latest
- docker tag ivct/testapp:po-$VERSION ivct/testapp:po-$TRAVIS_BRANCH-latest
- docker tag ivct/testapp:ma-$VERSION ivct/testapp:ma-$TRAVIS_BRANCH-latest
- docker push ivct/testapp

before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
