// This file was generated by the TNO Bean Generator.
// Any modifications to this file will be lost upon re-generation.
// Generated on: 2020/03/27 12:19:05

package nl.tno.rpr.interactions;

import nl.tno.rpr.datatypes.AcknowledgeFlagEnum16;
import nl.tno.rpr.datatypes.EntityIdentifierStruct;
import nl.tno.rpr.datatypes.ResponseFlagEnum16;

/**
 * A Simulation Management (SIMAN) interaction designed to acknowledge receipt of a SIMAN PDU from a
 * Simulation Manager federate and to inform the Simulation Manager federate whether the federate
 * has implemented the request.
 */
public class Acknowledge {

  /** The DIS entity ID of the entity or application sending the interaction. */
  EntityIdentifierStruct OriginatingEntity;

  /**
   * The DIS entity ID of the entity or application which is the intended recipient of the
   * interaction.
   */
  EntityIdentifierStruct ReceivingEntity;

  /**
   * This field matches this response with the specific StartResume, StopFreeze, CreateEntity or
   * RemoveEntity interaction sent by the simulation manager.
   */
  int RequestIdentifier;

  /** The type of interaction being acknowledged. */
  AcknowledgeFlagEnum16 AcknowledgeFlag;

  /** The type of response made to the interaction by the recipient. */
  ResponseFlagEnum16 ResponseFlag;

  public EntityIdentifierStruct getOriginatingEntity() {
    return this.OriginatingEntity;
  }

  public void setOriginatingEntity(EntityIdentifierStruct OriginatingEntity) {
    this.OriginatingEntity = OriginatingEntity;
  }

  public EntityIdentifierStruct getReceivingEntity() {
    return this.ReceivingEntity;
  }

  public void setReceivingEntity(EntityIdentifierStruct ReceivingEntity) {
    this.ReceivingEntity = ReceivingEntity;
  }

  public int getRequestIdentifier() {
    return this.RequestIdentifier;
  }

  public void setRequestIdentifier(int RequestIdentifier) {
    this.RequestIdentifier = RequestIdentifier;
  }

  public AcknowledgeFlagEnum16 getAcknowledgeFlag() {
    return this.AcknowledgeFlag;
  }

  public void setAcknowledgeFlag(AcknowledgeFlagEnum16 AcknowledgeFlag) {
    this.AcknowledgeFlag = AcknowledgeFlag;
  }

  public ResponseFlagEnum16 getResponseFlag() {
    return this.ResponseFlag;
  }

  public void setResponseFlag(ResponseFlagEnum16 ResponseFlag) {
    this.ResponseFlag = ResponseFlag;
  }
}
