// This file was generated by the TNO Bean Generator.
// Any modifications to this file will be lost upon re-generation.
// Generated on: 2020/03/27 12:19:05

package nl.tno.rpr.interactions;

import nl.tno.rpr.datatypes.RelativePositionStruct;

/**
 * Specifies the occurrence of a transient acoustic event such as torpedo tube floodings, hatch
 * slams, and wrench drops.
 */
public class AcousticTransient {

  /** Index into a data base of transient acoustic events */
  short ActivityCode;

  /** The current state of the activity specified by the activity code */
  short ActivityParameter;

  /** The Object Instance ID of the object emitting the sound */
  String HostObjectIdentifier;

  /** The location of the sound relative to the hosts coordinate system */
  RelativePositionStruct RelativePosition;

  public short getActivityCode() {
    return this.ActivityCode;
  }

  public void setActivityCode(short ActivityCode) {
    this.ActivityCode = ActivityCode;
  }

  public short getActivityParameter() {
    return this.ActivityParameter;
  }

  public void setActivityParameter(short ActivityParameter) {
    this.ActivityParameter = ActivityParameter;
  }

  public String getHostObjectIdentifier() {
    return this.HostObjectIdentifier;
  }

  public void setHostObjectIdentifier(String HostObjectIdentifier) {
    this.HostObjectIdentifier = HostObjectIdentifier;
  }

  public RelativePositionStruct getRelativePosition() {
    return this.RelativePosition;
  }

  public void setRelativePosition(RelativePositionStruct RelativePosition) {
    this.RelativePosition = RelativePosition;
  }
}
