// This file was generated by the TNO Bean Generator.
// Any modifications to this file will be lost upon re-generation.
// Generated on: 2020/03/27 12:19:05

package nl.tno.rpr.interactions;

import nl.tno.rpr.datatypes.ActionEnum32;

/**
 * A Simulation Management (SIMAN) interaction sent from a Simulation Manager federate to one or
 * more specific object instances to request that they perform a specified action.
 */
public class ActionRequestToObject {

  /** The list of objects that are the intended recipients of this interaction. */
  String[] ObjectIdentifiers;

  /** The action that the recipient(s) are intended to perform. */
  ActionEnum32 ActionRequestCode;

  public String[] getObjectIdentifiers() {
    return this.ObjectIdentifiers;
  }

  public void setObjectIdentifiers(String[] ObjectIdentifiers) {
    this.ObjectIdentifiers = ObjectIdentifiers;
  }

  public ActionEnum32 getActionRequestCode() {
    return this.ActionRequestCode;
  }

  public void setActionRequestCode(ActionEnum32 ActionRequestCode) {
    this.ActionRequestCode = ActionRequestCode;
  }
}
