// This file was generated by the TNO Bean Generator.
// Any modifications to this file will be lost upon re-generation.
// Generated on: 2020/03/27 12:19:05

package nl.tno.rpr.interactions;

import nl.tno.rpr.datatypes.AttributeValuePairStruct;

/**
 * A Simulation Management (SIMAN) interaction, sent from a Simulation Manager federate to ask that
 * a specified attribute be set to a specified value.
 */
public class AttributeChangeRequest {

  /** The list of objects that are the intended recipients of this interaction. */
  String[] ObjectIdentifiers;

  /** The set of attributes and their values, that the recipients are asked to update. */
  AttributeValuePairStruct[] AttributeValueSet;

  public String[] getObjectIdentifiers() {
    return this.ObjectIdentifiers;
  }

  public void setObjectIdentifiers(String[] ObjectIdentifiers) {
    this.ObjectIdentifiers = ObjectIdentifiers;
  }

  public AttributeValuePairStruct[] getAttributeValueSet() {
    return this.AttributeValueSet;
  }

  public void setAttributeValueSet(AttributeValuePairStruct[] AttributeValueSet) {
    this.AttributeValueSet = AttributeValueSet;
  }
}
