// This file was generated by the TNO Bean Generator.
// Any modifications to this file will be lost upon re-generation.
// Generated on: 2020/03/27 12:19:05

package nl.tno.rpr.interactions;

import nl.tno.rpr.datatypes.BreachedStatusEnum8;

/**
 * An interaction sent to an environment manager to request the creation, modification, or deletion
 * of instances of the BreachablePointObject class.
 */
public class BreachablePointObjectTransaction extends PointObjectTransaction {

  /** Specifies the breached appearance of the object */
  BreachedStatusEnum8 BreachedStatus;

  public BreachedStatusEnum8 getBreachedStatus() {
    return this.BreachedStatus;
  }

  public void setBreachedStatus(BreachedStatusEnum8 BreachedStatus) {
    this.BreachedStatus = BreachedStatus;
  }
}
