// This file was generated by the TNO Bean Generator.
// Any modifications to this file will be lost upon re-generation.
// Generated on: 2020/03/27 12:19:05

package nl.tno.rpr.interactions;

import nl.tno.rpr.datatypes.ChemicalContentEnum32;

/**
 * An interaction sent to an environment manager to request the creation, modification, or deletion
 * of instances of the BurstPointObject class.
 */
public class BurstPointObjectTransaction extends PointObjectTransaction {

  /** Specifies the opacity of the smoke */
  int PercentOpacity;

  /**
   * Specifies the radius of the cylinder approximating an individual smoke burst ; for multiple
   * bursts, the center bottom of each cylinder is calculated based on the model used to represent
   * the multiple bursts
   */
  int CylinderSize;

  /**
   * Specifies the height of the cylinder approximating an individual smoke burst ; for multiple
   * bursts, the center bottom of each cylinder is calculated based on the model used to represent
   * the multiple bursts
   */
  int CylinderHeight;

  /** Specifies the number of bursts in the instance of tactical smoke */
  int NumberOfBursts;

  /** Specifies the chemical content of the smoke */
  ChemicalContentEnum32 ChemicalContent;

  public int getPercentOpacity() {
    return this.PercentOpacity;
  }

  public void setPercentOpacity(int PercentOpacity) {
    this.PercentOpacity = PercentOpacity;
  }

  public int getCylinderSize() {
    return this.CylinderSize;
  }

  public void setCylinderSize(int CylinderSize) {
    this.CylinderSize = CylinderSize;
  }

  public int getCylinderHeight() {
    return this.CylinderHeight;
  }

  public void setCylinderHeight(int CylinderHeight) {
    this.CylinderHeight = CylinderHeight;
  }

  public int getNumberOfBursts() {
    return this.NumberOfBursts;
  }

  public void setNumberOfBursts(int NumberOfBursts) {
    this.NumberOfBursts = NumberOfBursts;
  }

  public ChemicalContentEnum32 getChemicalContent() {
    return this.ChemicalContent;
  }

  public void setChemicalContent(ChemicalContentEnum32 ChemicalContent) {
    this.ChemicalContent = ChemicalContent;
  }
}
