// This file was generated by the TNO Bean Generator.
// Any modifications to this file will be lost upon re-generation.
// Generated on: 2020/03/27 12:19:05

package nl.tno.rpr.interactions;

import nl.tno.rpr.datatypes.CollisionTypeEnum8;
import nl.tno.rpr.datatypes.EventIdentifierStruct;
import nl.tno.rpr.datatypes.RelativePositionStruct;
import nl.tno.rpr.datatypes.VelocityVectorStruct;

/** The act or instance of coming together with solid impact. */
public class Collision {

  /** The object instance ID of the object that the issuing object has collided with. */
  String CollidingObjectIdentifier;

  /** The mass of the issuing object. */
  float IssuingObjectMass;

  /** The velocity vector of the issuing object at the moment of impact. */
  VelocityVectorStruct IssuingObjectVelocityVector;

  /** The type of collision. */
  CollisionTypeEnum8 CollisionType;

  /**
   * The location of the collision relative to the object that the issuing object has collided with.
   */
  RelativePositionStruct CollisionLocation;

  /** An ID assigned by the issuing object to associate related collision events. */
  EventIdentifierStruct EventIdentifier;

  /**
   * The object instance ID of the object that has detected the collision and issued the collision
   * interaction.
   */
  String IssuingObjectIdentifier;

  public String getCollidingObjectIdentifier() {
    return this.CollidingObjectIdentifier;
  }

  public void setCollidingObjectIdentifier(String CollidingObjectIdentifier) {
    this.CollidingObjectIdentifier = CollidingObjectIdentifier;
  }

  public float getIssuingObjectMass() {
    return this.IssuingObjectMass;
  }

  public void setIssuingObjectMass(float IssuingObjectMass) {
    this.IssuingObjectMass = IssuingObjectMass;
  }

  public VelocityVectorStruct getIssuingObjectVelocityVector() {
    return this.IssuingObjectVelocityVector;
  }

  public void setIssuingObjectVelocityVector(VelocityVectorStruct IssuingObjectVelocityVector) {
    this.IssuingObjectVelocityVector = IssuingObjectVelocityVector;
  }

  public CollisionTypeEnum8 getCollisionType() {
    return this.CollisionType;
  }

  public void setCollisionType(CollisionTypeEnum8 CollisionType) {
    this.CollisionType = CollisionType;
  }

  public RelativePositionStruct getCollisionLocation() {
    return this.CollisionLocation;
  }

  public void setCollisionLocation(RelativePositionStruct CollisionLocation) {
    this.CollisionLocation = CollisionLocation;
  }

  public EventIdentifierStruct getEventIdentifier() {
    return this.EventIdentifier;
  }

  public void setEventIdentifier(EventIdentifierStruct EventIdentifier) {
    this.EventIdentifier = EventIdentifier;
  }

  public String getIssuingObjectIdentifier() {
    return this.IssuingObjectIdentifier;
  }

  public void setIssuingObjectIdentifier(String IssuingObjectIdentifier) {
    this.IssuingObjectIdentifier = IssuingObjectIdentifier;
  }
}
