// This file was generated by the TNO Bean Generator.
// Any modifications to this file will be lost upon re-generation.
// Generated on: 2020/03/27 12:19:05

package nl.tno.rpr.interactions;

/**
 * An interaction sent to an environment manager to request the creation, modification, or deletion
 * of instances of the CraterObject class.
 */
public class CraterObjectTransaction extends PointObjectTransaction {

  /**
   * Specifies the diameter of the crater, where the center of the crater is at the point object
   * location
   */
  int CraterSize;

  public int getCraterSize() {
    return this.CraterSize;
  }

  public void setCraterSize(int CraterSize) {
    this.CraterSize = CraterSize;
  }
}
