// This file was generated by the TNO Bean Generator.
// Any modifications to this file will be lost upon re-generation.
// Generated on: 2020/03/27 12:19:05

package nl.tno.rpr.interactions;

import nl.tno.rpr.datatypes.AttributeValuePairStruct;

/**
 * A Simulation Management (SIMAN) interaction, sent from a Simulation Manager federate to another
 * federate requesting that it create an object instance of a particular type.
 */
public class CreateObjectRequest {

  /** The class of object to be created. */
  int ObjectClass;

  /** The set of attributes, and associated values, to be used to initialize the object. */
  AttributeValuePairStruct[] AttributeValueSet;

  /**
   * The Request ID is a monotonically increasing integer identifier inserted by the Simulation
   * Manager into all Simulation management interactions. It is used as a unique identifier to
   * identify the latest in a series of competing requests and identifying acknowledgements.
   */
  int RequestIdentifier;

  public int getObjectClass() {
    return this.ObjectClass;
  }

  public void setObjectClass(int ObjectClass) {
    this.ObjectClass = ObjectClass;
  }

  public AttributeValuePairStruct[] getAttributeValueSet() {
    return this.AttributeValueSet;
  }

  public void setAttributeValueSet(AttributeValuePairStruct[] AttributeValueSet) {
    this.AttributeValueSet = AttributeValueSet;
  }

  public int getRequestIdentifier() {
    return this.RequestIdentifier;
  }

  public void setRequestIdentifier(int RequestIdentifier) {
    this.RequestIdentifier = RequestIdentifier;
  }
}
