// This file was generated by the TNO Bean Generator.
// Any modifications to this file will be lost upon re-generation.
// Generated on: 2020/03/27 12:19:05

package nl.tno.rpr.interactions;

import nl.tno.rpr.datatypes.ResponseFlagEnum16;

/**
 * A Simulation Management (SIMAN) interaction designed to acknowledge receipt of a
 * CreateObjectRequest from a Simulation Manager federate and to inform the Simulation Manager
 * federate whether the object creation was successful or not.
 */
public class CreateObjectResult {

  /** Indicates ability to comply. */
  ResponseFlagEnum16 CreateObjectResult;

  /**
   * This field matches this response with the specific CreateObject interaction sent by the
   * simulation manager.
   */
  int RequestIdentifier;

  public ResponseFlagEnum16 getCreateObjectResult() {
    return this.CreateObjectResult;
  }

  public void setCreateObjectResult(ResponseFlagEnum16 CreateObjectResult) {
    this.CreateObjectResult = CreateObjectResult;
  }

  public int getRequestIdentifier() {
    return this.RequestIdentifier;
  }

  public void setRequestIdentifier(int RequestIdentifier) {
    this.RequestIdentifier = RequestIdentifier;
  }
}
