// This file was generated by the TNO Bean Generator.
// Any modifications to this file will be lost upon re-generation.
// Generated on: 2020/03/27 12:19:05

package nl.tno.rpr.interactions;

import nl.tno.rpr.datatypes.DatumIdentifierEnum32;
import nl.tno.rpr.datatypes.EntityIdentifierStruct;

/**
 * A Simulation Management (SIMAN) interaction, sent from a Simulation Manager federate to request
 * that a federate supply the current values of specified data.
 */
public class DataQuery {

  /** The DIS entity ID of the entity or application sending the interaction. */
  EntityIdentifierStruct OriginatingEntity;

  /**
   * The DIS entity ID of the entity or application which is the intended recipient of the
   * interaction.
   */
  EntityIdentifierStruct ReceivingEntity;

  /**
   * The Request ID is a monotonically increasing integer identifier inserted by the Simulation
   * Manager into all Simulation management interactions. It is used as a unique identifier to
   * identify the latest in a series of competing requests and identifying acknowledgements.
   */
  int RequestIdentifier;

  /**
   * The interval between regular updates of the requested data. If this field is zero then the
   * recipient should only issue a single Data interaction in response to this interaction.
   */
  int TimeInterval;

  /**
   * The set of fixed length data items (types) that the recipient is requested to supply data for.
   */
  DatumIdentifierEnum32[] FixedDatumIdentifiers;

  /**
   * The set of variable length data items (types) that the recipient is requested to supply data
   * for.
   */
  DatumIdentifierEnum32[] VariableDatumIdentifiers;

  public EntityIdentifierStruct getOriginatingEntity() {
    return this.OriginatingEntity;
  }

  public void setOriginatingEntity(EntityIdentifierStruct OriginatingEntity) {
    this.OriginatingEntity = OriginatingEntity;
  }

  public EntityIdentifierStruct getReceivingEntity() {
    return this.ReceivingEntity;
  }

  public void setReceivingEntity(EntityIdentifierStruct ReceivingEntity) {
    this.ReceivingEntity = ReceivingEntity;
  }

  public int getRequestIdentifier() {
    return this.RequestIdentifier;
  }

  public void setRequestIdentifier(int RequestIdentifier) {
    this.RequestIdentifier = RequestIdentifier;
  }

  public int getTimeInterval() {
    return this.TimeInterval;
  }

  public void setTimeInterval(int TimeInterval) {
    this.TimeInterval = TimeInterval;
  }

  public DatumIdentifierEnum32[] getFixedDatumIdentifiers() {
    return this.FixedDatumIdentifiers;
  }

  public void setFixedDatumIdentifiers(DatumIdentifierEnum32[] FixedDatumIdentifiers) {
    this.FixedDatumIdentifiers = FixedDatumIdentifiers;
  }

  public DatumIdentifierEnum32[] getVariableDatumIdentifiers() {
    return this.VariableDatumIdentifiers;
  }

  public void setVariableDatumIdentifiers(DatumIdentifierEnum32[] VariableDatumIdentifiers) {
    this.VariableDatumIdentifiers = VariableDatumIdentifiers;
  }
}
