// This file was generated by the TNO Bean Generator.
// Any modifications to this file will be lost upon re-generation.
// Generated on: 2020/03/27 12:19:05

package nl.tno.rpr.interactions;

import nl.tno.rpr.datatypes.EntityIdentifierStruct;
import nl.tno.rpr.datatypes.FixedDatumStruct;
import nl.tno.rpr.datatypes.VariableDatumStruct;

/**
 * A Simulation Management (SIMAN) interaction designed to acknowledge either a) a DataQuery
 * interaction (in which case the Data interaction contains the results of the query) or b) a
 * SetData interaction (in which case the Data interaction contains the data that the federate was
 * able to set).
 */
public class Data {

  /** The DIS entity ID of the entity or application sending the interaction. */
  EntityIdentifierStruct OriginatingEntity;

  /**
   * The DIS entity ID of the entity or application which is the intended recipient of the
   * interaction.
   */
  EntityIdentifierStruct ReceivingEntity;

  /**
   * This field matches this response with the specific SetData or DataQuery interaction sent by the
   * simulation manager.
   */
  int RequestIdentifier;

  /**
   * The set of data items (types and values), of fixed length, that the recipient can return for
   * this interaction.
   */
  FixedDatumStruct[] FixedDatums;

  /**
   * The set of data items (types and values), of variable length, that the recipient can return for
   * this interaction.
   */
  VariableDatumStruct[] VariableDatumSet;

  public EntityIdentifierStruct getOriginatingEntity() {
    return this.OriginatingEntity;
  }

  public void setOriginatingEntity(EntityIdentifierStruct OriginatingEntity) {
    this.OriginatingEntity = OriginatingEntity;
  }

  public EntityIdentifierStruct getReceivingEntity() {
    return this.ReceivingEntity;
  }

  public void setReceivingEntity(EntityIdentifierStruct ReceivingEntity) {
    this.ReceivingEntity = ReceivingEntity;
  }

  public int getRequestIdentifier() {
    return this.RequestIdentifier;
  }

  public void setRequestIdentifier(int RequestIdentifier) {
    this.RequestIdentifier = RequestIdentifier;
  }

  public FixedDatumStruct[] getFixedDatums() {
    return this.FixedDatums;
  }

  public void setFixedDatums(FixedDatumStruct[] FixedDatums) {
    this.FixedDatums = FixedDatums;
  }

  public VariableDatumStruct[] getVariableDatumSet() {
    return this.VariableDatumSet;
  }

  public void setVariableDatumSet(VariableDatumStruct[] VariableDatumSet) {
    this.VariableDatumSet = VariableDatumSet;
  }
}
