// This file was generated by the TNO Bean Generator.
// Any modifications to this file will be lost upon re-generation.
// Generated on: 2020/03/27 12:19:05

package nl.tno.rpr.interactions;

import nl.tno.rpr.datatypes.AudioDataTypeStruct;

/**
 * A radio signal used to transmit voice/audio data encoded according to a standard encoding scheme.
 */
public class EncodedAudioRadioSignal extends RadioSignal {

  /** The data associated with the encoded audio radio signal */
  AudioDataTypeStruct AudioData;

  public AudioDataTypeStruct getAudioData() {
    return this.AudioData;
  }

  public void setAudioData(AudioDataTypeStruct AudioData) {
    this.AudioData = AudioData;
  }
}
