// This file was generated by the TNO Bean Generator.
// Any modifications to this file will be lost upon re-generation.
// Generated on: 2020/03/27 12:19:05

package nl.tno.rpr.interactions;

import nl.tno.rpr.datatypes.ExhaustSmokeStruct;

/**
 * An interaction sent to an environment manager to request the creation, modification, or deletion
 * of instances of the ExhaustSmokeObject class.
 */
public class ExhaustSmokeObjectTransaction extends LinearObjectTransaction {

  /** Specifies an exhaust smoke linear object */
  ExhaustSmokeStruct[] SegmentRecords;

  public ExhaustSmokeStruct[] getSegmentRecords() {
    return this.SegmentRecords;
  }

  public void setSegmentRecords(ExhaustSmokeStruct[] SegmentRecords) {
    this.SegmentRecords = SegmentRecords;
  }
}
