// This file was generated by the TNO Bean Generator.
// Any modifications to this file will be lost upon re-generation.
// Generated on: 2020/03/27 12:19:05

package nl.tno.rpr.interactions;

/** An interaction for modifying instances of the LinearObject class. */
public class LinearObjectTransaction extends EnvironmentObjectTransaction {}
