// This file was generated by the TNO Bean Generator.
// Any modifications to this file will be lost upon re-generation.
// Generated on: 2020/03/27 12:19:05

package nl.tno.rpr.interactions;

import nl.tno.rpr.datatypes.MinefieldLaneMarkerStruct;

/**
 * An interaction sent to an environment manager to request the creation, modification, or deletion
 * of instances of the MinefieldLaneMarkerObject class.
 */
public class MinefieldLaneMarkerObjectTransaction extends LinearObjectTransaction {

  /** Specifies a minefield lane marker linear object */
  MinefieldLaneMarkerStruct[] SegmentRecords;

  public MinefieldLaneMarkerStruct[] getSegmentRecords() {
    return this.SegmentRecords;
  }

  public void setSegmentRecords(MinefieldLaneMarkerStruct[] SegmentRecords) {
    this.SegmentRecords = SegmentRecords;
  }
}
