// This file was generated by the TNO Bean Generator.
// Any modifications to this file will be lost upon re-generation.
// Generated on: 2020/03/27 12:19:05

package nl.tno.rpr.interactions;

/** A response to a MinefieldQuery providing information on individual mines within a minefield. */
public class MinefieldResponseNACK {

  /** Identifies the minefield to which this query is addressed */
  String MinefieldIdentifier;

  /** Specifies the record numbers that were not received in a sequence of minefield records */
  byte[] MissingRecordNumbers;

  /** Identifies the minefield query request */
  byte RequestIdentifier;

  /** Identifies the entity that requested the information from the minefield simulation */
  String RequestingEntityIdentifier;

  public String getMinefieldIdentifier() {
    return this.MinefieldIdentifier;
  }

  public void setMinefieldIdentifier(String MinefieldIdentifier) {
    this.MinefieldIdentifier = MinefieldIdentifier;
  }

  public byte[] getMissingRecordNumbers() {
    return this.MissingRecordNumbers;
  }

  public void setMissingRecordNumbers(byte[] MissingRecordNumbers) {
    this.MissingRecordNumbers = MissingRecordNumbers;
  }

  public byte getRequestIdentifier() {
    return this.RequestIdentifier;
  }

  public void setRequestIdentifier(byte RequestIdentifier) {
    this.RequestIdentifier = RequestIdentifier;
  }

  public String getRequestingEntityIdentifier() {
    return this.RequestingEntityIdentifier;
  }

  public void setRequestingEntityIdentifier(String RequestingEntityIdentifier) {
    this.RequestingEntityIdentifier = RequestingEntityIdentifier;
  }
}
