// This file was generated by the TNO Bean Generator.
// Any modifications to this file will be lost upon re-generation.
// Generated on: 2020/03/27 12:19:05

package nl.tno.rpr.interactions;

import nl.tno.rpr.datatypes.AcknowledgementProtocolEnum8;
import nl.tno.rpr.datatypes.EntityIdentifierStruct;
import nl.tno.rpr.datatypes.EventTypeEnum32;
import nl.tno.rpr.datatypes.RecordSetStruct;

/**
 * A Simulation Management (SIMAN) interaction designed to acknowledge receipt of a RecordQueryR or
 * SetRecordR interaction from a Simulation Manager federate and to inform the Simulation Manager
 * federate whether the federate has implemented the request.
 */
public class RecordR {

  /** The DIS entity ID of the entity or application sending the interaction. */
  EntityIdentifierStruct OriginatingEntity;

  /**
   * The DIS entity ID of the entity or application which is the intended recipient of the
   * interaction.
   */
  EntityIdentifierStruct ReceivingEntity;

  /**
   * This field matches this response with the specific RecordQueryR or SetRecordR interaction sent
   * by the simulation manager.
   */
  int RequestIdentifier;

  /** The type of event that caused the RecordR interaction to be issued. */
  EventTypeEnum32 EventType;

  /** The acknowledgement protocol to be used for the transaction */
  AcknowledgementProtocolEnum8 AcknowledgementProtocol;

  /**
   * Used to identify the serial number of the RecordR interaction when more than one interaction is
   * used to report record values.
   */
  int ResponseSerialNumber;

  /** The set of records containing the information requested */
  RecordSetStruct[] RecordSetData;

  public EntityIdentifierStruct getOriginatingEntity() {
    return this.OriginatingEntity;
  }

  public void setOriginatingEntity(EntityIdentifierStruct OriginatingEntity) {
    this.OriginatingEntity = OriginatingEntity;
  }

  public EntityIdentifierStruct getReceivingEntity() {
    return this.ReceivingEntity;
  }

  public void setReceivingEntity(EntityIdentifierStruct ReceivingEntity) {
    this.ReceivingEntity = ReceivingEntity;
  }

  public int getRequestIdentifier() {
    return this.RequestIdentifier;
  }

  public void setRequestIdentifier(int RequestIdentifier) {
    this.RequestIdentifier = RequestIdentifier;
  }

  public EventTypeEnum32 getEventType() {
    return this.EventType;
  }

  public void setEventType(EventTypeEnum32 EventType) {
    this.EventType = EventType;
  }

  public AcknowledgementProtocolEnum8 getAcknowledgementProtocol() {
    return this.AcknowledgementProtocol;
  }

  public void setAcknowledgementProtocol(AcknowledgementProtocolEnum8 AcknowledgementProtocol) {
    this.AcknowledgementProtocol = AcknowledgementProtocol;
  }

  public int getResponseSerialNumber() {
    return this.ResponseSerialNumber;
  }

  public void setResponseSerialNumber(int ResponseSerialNumber) {
    this.ResponseSerialNumber = ResponseSerialNumber;
  }

  public RecordSetStruct[] getRecordSetData() {
    return this.RecordSetData;
  }

  public void setRecordSetData(RecordSetStruct[] RecordSetData) {
    this.RecordSetData = RecordSetData;
  }
}
