// This file was generated by the TNO Bean Generator.
// Any modifications to this file will be lost upon re-generation.
// Generated on: 2020/03/27 12:19:05

package nl.tno.rpr.interactions;

/**
 * A Simulation Management (SIMAN) interaction designed to acknowledge receipt of a
 * RemoveObjectRequestR interaction, and to inform the Simulation Manager federate whether the
 * removal was successful or not.
 */
public class RemoveObjectResultR extends RemoveObjectResult {}
