// This file was generated by the TNO Bean Generator.
// Any modifications to this file will be lost upon re-generation.
// Generated on: 2020/03/27 12:19:05

package nl.tno.rpr.interactions;

import nl.tno.rpr.datatypes.ResponseFlagEnum16;

/**
 * A Simulation Management (SIMAN) interaction designed to acknowledge receipt of a
 * RemoveObjectRequest interaction, and to inform the Simulation Manager federate whether the
 * removal was successful or not.
 */
public class RemoveObjectResult {

  /** Indicates ability to comply. */
  ResponseFlagEnum16 RemoveObjectResult;

  /**
   * This field matches this response with the specific RemoveObject interaction sent by the
   * simulation manager.
   */
  int RequestIdentifier;

  public ResponseFlagEnum16 getRemoveObjectResult() {
    return this.RemoveObjectResult;
  }

  public void setRemoveObjectResult(ResponseFlagEnum16 RemoveObjectResult) {
    this.RemoveObjectResult = RemoveObjectResult;
  }

  public int getRequestIdentifier() {
    return this.RequestIdentifier;
  }

  public void setRequestIdentifier(int RequestIdentifier) {
    this.RequestIdentifier = RequestIdentifier;
  }
}
