// This file was generated by the TNO Bean Generator.
// Any modifications to this file will be lost upon re-generation.
// Generated on: 2020/03/27 12:19:05

package nl.tno.rpr.interactions;

/**
 * Communicates the canceling of a service function by either the receiving or the supplying entity.
 */
public class ResupplyCancel {

  /** Object that is receiving supplies */
  String ReceivingObject;

  /** Object that has offered supplies */
  String SupplyingObject;

  public String getReceivingObject() {
    return this.ReceivingObject;
  }

  public void setReceivingObject(String ReceivingObject) {
    this.ReceivingObject = ReceivingObject;
  }

  public String getSupplyingObject() {
    return this.SupplyingObject;
  }

  public void setSupplyingObject(String SupplyingObject) {
    this.SupplyingObject = SupplyingObject;
  }
}
