// This file was generated by the TNO Bean Generator.
// Any modifications to this file will be lost upon re-generation.
// Generated on: 2020/03/27 12:19:05

package nl.tno.rpr.interactions;

import nl.tno.rpr.datatypes.SupplyStruct;

/** Communicates the offer of supplies from a supplying entity to a receiving entity. */
public class ResupplyOffer {

  /** Object that the supplies are being offered to. */
  String ReceivingObject;

  /** Object that is offering the supplies */
  String SupplyingObject;

  /** List of supplies that are offered. */
  SupplyStruct[] SuppliesData;

  public String getReceivingObject() {
    return this.ReceivingObject;
  }

  public void setReceivingObject(String ReceivingObject) {
    this.ReceivingObject = ReceivingObject;
  }

  public String getSupplyingObject() {
    return this.SupplyingObject;
  }

  public void setSupplyingObject(String SupplyingObject) {
    this.SupplyingObject = SupplyingObject;
  }

  public SupplyStruct[] getSuppliesData() {
    return this.SuppliesData;
  }

  public void setSuppliesData(SupplyStruct[] SuppliesData) {
    this.SuppliesData = SuppliesData;
  }
}
