// This file was generated by the TNO Bean Generator.
// Any modifications to this file will be lost upon re-generation.
// Generated on: 2020/03/27 12:19:05

package nl.tno.rpr.interactions;

/**
 * An interaction sent to an environment manager to request the creation, modification, or deletion
 * of instances of the RibbonBridgeObject class.
 */
public class RibbonBridgeObjectTransaction extends PointObjectTransaction {

  /** Specifies the number of segments composing the ribbon bridge */
  int NumberOfSegments;

  public int getNumberOfSegments() {
    return this.NumberOfSegments;
  }

  public void setNumberOfSegments(int NumberOfSegments) {
    this.NumberOfSegments = NumberOfSegments;
  }
}
