// This file was generated by the TNO Bean Generator.
// Any modifications to this file will be lost upon re-generation.
// Generated on: 2020/03/27 12:19:05

package nl.tno.rpr.interactions;

/**
 * An interaction sent to an environment manager to request the creation, modification, or deletion
 * of instances of the StructureObject class.
 */
public class StructureObjectTransaction extends PointObjectTransaction {}
