// This file was generated by the TNO Bean Generator.
// Any modifications to this file will be lost upon re-generation.
// Generated on: 2020/03/27 12:19:05

package nl.tno.rpr.interactions;

import nl.tno.rpr.datatypes.EntityTypeStruct;
import nl.tno.rpr.datatypes.EventIdentifierStruct;
import nl.tno.rpr.datatypes.FuseTypeEnum16;
import nl.tno.rpr.datatypes.VelocityVectorStruct;
import nl.tno.rpr.datatypes.WarheadTypeEnum16;
import nl.tno.rpr.datatypes.WorldLocationStruct;

/** Communicates information associated with the firing or launch of a munition. */
public class WeaponFire {

  /**
   * An ID, generated by the issuing federate, used to associate related fire and detonation events.
   */
  EventIdentifierStruct EventIdentifier;

  /** The range used in the fire control solution. Zero if the range is unknown or inapplicable. */
  float FireControlSolutionRange;

  /**
   * A unique index to identify the fire mission (used to associate weapon fire interactions in a
   * single fire mission).
   */
  int FireMissionIndex;

  /** The location, in world coordinates, from which the munition was launched. */
  WorldLocationStruct FiringLocation;

  /** The object instance ID of the entity firing the munition. */
  String FiringObjectIdentifier;

  /** The type of fuse on the munition. */
  FuseTypeEnum16 FuseType;

  /** The velocity vector of the munition when fired. */
  VelocityVectorStruct InitialVelocityVector;

  /** The object instance ID of the fired munition, if an object instance is registered. */
  String MunitionObjectIdentifier;

  /** The type of munition being fired. */
  EntityTypeStruct MunitionType;

  /** The number of rounds fired in the burst. */
  short QuantityFired;

  /** The rate of fire in rounds per minute when quantity > 1. Zero otherwise. */
  short RateOfFire;

  /** The object instance ID of the intended target (if any). */
  String TargetObjectIdentifier;

  /** The type of warhead fitted to the munition being fired. */
  WarheadTypeEnum16 WarheadType;

  public EventIdentifierStruct getEventIdentifier() {
    return this.EventIdentifier;
  }

  public void setEventIdentifier(EventIdentifierStruct EventIdentifier) {
    this.EventIdentifier = EventIdentifier;
  }

  public float getFireControlSolutionRange() {
    return this.FireControlSolutionRange;
  }

  public void setFireControlSolutionRange(float FireControlSolutionRange) {
    this.FireControlSolutionRange = FireControlSolutionRange;
  }

  public int getFireMissionIndex() {
    return this.FireMissionIndex;
  }

  public void setFireMissionIndex(int FireMissionIndex) {
    this.FireMissionIndex = FireMissionIndex;
  }

  public WorldLocationStruct getFiringLocation() {
    return this.FiringLocation;
  }

  public void setFiringLocation(WorldLocationStruct FiringLocation) {
    this.FiringLocation = FiringLocation;
  }

  public String getFiringObjectIdentifier() {
    return this.FiringObjectIdentifier;
  }

  public void setFiringObjectIdentifier(String FiringObjectIdentifier) {
    this.FiringObjectIdentifier = FiringObjectIdentifier;
  }

  public FuseTypeEnum16 getFuseType() {
    return this.FuseType;
  }

  public void setFuseType(FuseTypeEnum16 FuseType) {
    this.FuseType = FuseType;
  }

  public VelocityVectorStruct getInitialVelocityVector() {
    return this.InitialVelocityVector;
  }

  public void setInitialVelocityVector(VelocityVectorStruct InitialVelocityVector) {
    this.InitialVelocityVector = InitialVelocityVector;
  }

  public String getMunitionObjectIdentifier() {
    return this.MunitionObjectIdentifier;
  }

  public void setMunitionObjectIdentifier(String MunitionObjectIdentifier) {
    this.MunitionObjectIdentifier = MunitionObjectIdentifier;
  }

  public EntityTypeStruct getMunitionType() {
    return this.MunitionType;
  }

  public void setMunitionType(EntityTypeStruct MunitionType) {
    this.MunitionType = MunitionType;
  }

  public short getQuantityFired() {
    return this.QuantityFired;
  }

  public void setQuantityFired(short QuantityFired) {
    this.QuantityFired = QuantityFired;
  }

  public short getRateOfFire() {
    return this.RateOfFire;
  }

  public void setRateOfFire(short RateOfFire) {
    this.RateOfFire = RateOfFire;
  }

  public String getTargetObjectIdentifier() {
    return this.TargetObjectIdentifier;
  }

  public void setTargetObjectIdentifier(String TargetObjectIdentifier) {
    this.TargetObjectIdentifier = TargetObjectIdentifier;
  }

  public WarheadTypeEnum16 getWarheadType() {
    return this.WarheadType;
  }

  public void setWarheadType(WarheadTypeEnum16 WarheadType) {
    this.WarheadType = WarheadType;
  }
}
