// This file was generated by the TNO Bean Generator.
// Any modifications to this file will be lost upon re-generation.
// Generated on: 2020/03/27 12:19:05

package nl.tno.rpr.datatypes;

/** Acknowledgment flags */
public enum AcknowledgeFlagEnum16 {
  CreateEntity((short) 1),
  RemoveEntity((short) 2),
  StartResume((short) 3),
  StopFreeze((short) 4),
  TransferOwnership((short) 5);

  private final short value;

  private AcknowledgeFlagEnum16(short value) {
    this.value = value;
  }

  public short getValue() {
    return value;
  }
}
