// This file was generated by the TNO Bean Generator.
// Any modifications to this file will be lost upon re-generation.
// Generated on: 2020/03/27 12:19:05

package nl.tno.rpr.datatypes;

/** Required reliability service */
public enum AcknowledgementProtocolEnum8 {
  Acknowledged((byte) 0),
  Unacknowledged((byte) 1);

  private final byte value;

  private AcknowledgementProtocolEnum8(byte value) {
    this.value = value;
  }

  public byte getValue() {
    return value;
  }
}
