// This file was generated by the TNO Bean Generator.
// Any modifications to this file will be lost upon re-generation.
// Generated on: 2020/03/27 12:19:05

package nl.tno.rpr.datatypes;

/** Acoustic scan pattern */
public enum ActiveSonarScanPatternEnum16 {
  ScanPatternNotUsed((short) 0),
  Conical((short) 1),
  Helical((short) 2),
  Raster((short) 3),
  SectorSearch((short) 4),
  ContinuousSearch((short) 5);

  private final short value;

  private ActiveSonarScanPatternEnum16(short value) {
    this.value = value;
  }

  public short getValue() {
    return value;
  }
}
