// This file was generated by the TNO Bean Generator.
// Any modifications to this file will be lost upon re-generation.
// Generated on: 2020/03/27 12:19:05

package nl.tno.rpr.datatypes;

/** Acoustic system name */
public enum ActiveSonarEnum16 {
  Other((short) 0),
  AN_BQQ__5((short) 1),
  AN_SSQ__62((short) 2),
  AN_SQS__23((short) 3),
  AN_SQS__26((short) 4),
  AN_SQS__53((short) 5),
  ALFS((short) 6),
  LFA((short) 7),
  AN_AQS__901((short) 8),
  AN_AQS__902((short) 9);

  private final short value;

  private ActiveSonarEnum16(short value) {
    this.value = value;
  }

  public short getValue() {
    return value;
  }
}
