// This file was generated by the TNO Bean Generator.
// Any modifications to this file will be lost upon re-generation.
// Generated on: 2020/03/27 12:19:05

package nl.tno.rpr.datatypes;

/** Action ID */
public enum ActionEnum32 {
  Other(0),
  LocalStorageOfTheRequestedInformation(1),
  InformSimulationManagerOfRanOutOfAmmunitionEvent(2),
  InformSimulationManagerOfKilledInActionEvent(3),
  InformSimulationManagerOfDamageEvent(4),
  InformSimulationManagerOfMobilityDisabledEvent(5),
  InformSimulationManagerOfFireDisabledEvent(6),
  InformSimulationManagerOfRanOutOfFuelEvent(7),
  RecallCheckpointData(8),
  RecallInitialParameters(9),
  InitiateTetherLead(10),
  InitiateTetherFollow(11),
  Untether(12),
  InitiateServiceStationResupply(13),
  InitiateTailgateResupply(14),
  InitiateHitchLead(15),
  InitiateHitchFollow(16),
  Unhitch(17),
  Mount(18),
  Dismount(19),
  StartDailyReadinessCheck(20),
  StopDailyReadinessCheck(21),
  DataQuery(22),
  StatusRequest(23),
  SendObjectStateData(24),
  Reconstitute(25),
  LockSiteConfiguration(26),
  UnlockSiteConfiguration(27),
  UpdateSiteConfiguration(28),
  QuerySiteConfiguration(29),
  TetheringInformation(30),
  MountIntent(31),
  AcceptSubscription(33),
  Unsubscribe(34),
  TeleportEntity(35),
  ChangeAggregateState(36),
  RequestStartPDU(37),
  WakeupGetReadyForInitialization(38),
  InitializeInternalParameters(39),
  SendPlanData(40),
  SynchronizeInternalClocks(41),
  Run(42),
  SaveInternalParameters(43),
  SimulateMalfunction(44),
  JoinExercise(45),
  ResignExercise(46),
  TimeAdvance(47),
  TACCSF_LOS_Request__Type1(100),
  TACCSF_LOS_Request__Type2(101);

  private final int value;

  private ActionEnum32(int value) {
    this.value = value;
  }

  public int getValue() {
    return value;
  }
}
