// This file was generated by the TNO Bean Generator.
// Any modifications to this file will be lost upon re-generation.
// Generated on: 2020/03/27 12:19:05

package nl.tno.rpr.datatypes;

/** Request status */
public enum ActionResultEnum32 {
  Other(0),
  Pending(1),
  Executing(2),
  PartiallyComplete(3),
  Complete(4),
  RequestRejected(5),
  RetransmitRequestNow(6),
  RetransmitRequestLater(7),
  InvalidTimeParameters(8),
  SimulationTimeExceeded(9),
  RequestDone(10),
  TACCSF_LOS_Reply__Type1(100),
  TACCSF_LOS_Reply__Type2(101),
  JoinExerciseRequestRejected(201);

  private final int value;

  private ActionResultEnum32(int value) {
    this.value = value;
  }

  public int getValue() {
    return value;
  }
}
