// This file was generated by the TNO Bean Generator.
// Any modifications to this file will be lost upon re-generation.
// Generated on: 2020/03/27 12:19:05

package nl.tno.rpr.datatypes;

/** The current function being performed by the sonar */
public enum ActiveSonarFunctionCodeEnum8 {
  Other((byte) 0),
  PlatformSearch_detect_track((byte) 1),
  Navigation((byte) 2),
  MineHunting((byte) 3),
  WeaponSearch_detect_track_detect((byte) 4);

  private final byte value;

  private ActiveSonarFunctionCodeEnum8(byte value) {
    this.value = value;
  }

  public byte getValue() {
    return value;
  }
}
