// This file was generated by the TNO Bean Generator.
// Any modifications to this file will be lost upon re-generation.
// Generated on: 2020/03/27 12:19:05

package nl.tno.rpr.datatypes;

/** Aggregate state */
public enum AggregateStateEnum8 {
  Other((byte) 0),
  Aggregated((byte) 1),
  Disaggregated((byte) 2),
  FullyDisaggregated((byte) 3),
  PseudoDisaggregated((byte) 4),
  PartiallyDisaggregated((byte) 5);

  private final byte value;

  private AggregateStateEnum8(byte value) {
    this.value = value;
  }

  public byte getValue() {
    return value;
  }
}
