// This file was generated by the TNO Bean Generator.
// Any modifications to this file will be lost upon re-generation.
// Generated on: 2020/03/27 12:19:05

package nl.tno.rpr.datatypes;

/** Detailed modulation types for Amplitude Modulation */
public enum AmplitudeModulationTypeEnum16 {
  Other((short) 0),
  AudioFrequencyShiftKeying((short) 1),
  AmplitudeModulation((short) 2),
  ContinuousWaveModulation((short) 3),
  DoubleSideband((short) 4),
  IndependentSideband((short) 5),
  SSB_LowerSideband((short) 6),
  SSB_FullCarrier((short) 7),
  SSB_ReducedCarrier((short) 8),
  SSB_UpperSideband((short) 9),
  VestigialSideband((short) 10);

  private final short value;

  private AmplitudeModulationTypeEnum16(short value) {
    this.value = value;
  }

  public short getValue() {
    return value;
  }
}
