// This file was generated by the TNO Bean Generator.
// Any modifications to this file will be lost upon re-generation.
// Generated on: 2020/03/27 12:19:05

package nl.tno.rpr.datatypes;

/** The rate at which the orientation is changing over time, in body coordinates. */
public class AngularVelocityVectorStruct {

  /** Acceleration component about the X axis. */
  float XAngularVelocity;

  /** Acceleration component about the Y axis. */
  float YAngularVelocity;

  /** Acceleration component about the Z axis. */
  float ZAngularVelocity;

  public float getXAngularVelocity() {
    return this.XAngularVelocity;
  }

  public void setXAngularVelocity(float XAngularVelocity) {
    this.XAngularVelocity = XAngularVelocity;
  }

  public float getYAngularVelocity() {
    return this.YAngularVelocity;
  }

  public void setYAngularVelocity(float YAngularVelocity) {
    this.YAngularVelocity = YAngularVelocity;
  }

  public float getZAngularVelocity() {
    return this.ZAngularVelocity;
  }

  public void setZAngularVelocity(float ZAngularVelocity) {
    this.ZAngularVelocity = ZAngularVelocity;
  }
}
