// This file was generated by the TNO Bean Generator.
// Any modifications to this file will be lost upon re-generation.
// Generated on: 2020/03/27 12:19:05

package nl.tno.rpr.datatypes;

/** The radiation pattern from an antenna. */
public enum AntennaPatternTypeEnum32 {
  OmniDirectional(0),
  Beam(1),
  SphericalHarmonic(2);

  private final int value;

  private AntennaPatternTypeEnum32(int value) {
    this.value = value;
  }

  public int getValue() {
    return value;
  }
}
