// This file was generated by the TNO Bean Generator.
// Any modifications to this file will be lost upon re-generation.
// Generated on: 2020/03/27 12:19:05

package nl.tno.rpr.datatypes;

/** Breached appearance */
public enum BreachedStatusEnum8 {
  NoBreaching((byte) 0),
  SlightBreaching((byte) 1),
  ModerateBreaching((byte) 2),
  Cleared((byte) 3);

  private final byte value;

  private BreachedStatusEnum8(byte value) {
    this.value = value;
  }

  public byte getValue() {
    return value;
  }
}
