// This file was generated by the TNO Bean Generator.
// Any modifications to this file will be lost upon re-generation.
// Generated on: 2020/03/27 12:19:05

package nl.tno.rpr.datatypes;

/** Record specifying the characteristics of a breach linear object segment */
public class BreachStruct {

  /** Specifies the breach linear object segment characteristics */
  LinearSegmentStruct SegmentParameters;

  /** Padding to 64 bits */
  byte[] Padding;

  public LinearSegmentStruct getSegmentParameters() {
    return this.SegmentParameters;
  }

  public void setSegmentParameters(LinearSegmentStruct SegmentParameters) {
    this.SegmentParameters = SegmentParameters;
  }

  public byte[] getPadding() {
    return this.Padding;
  }

  public void setPadding(byte[] Padding) {
    this.Padding = Padding;
  }
}
