// This file was generated by the TNO Bean Generator.
// Any modifications to this file will be lost upon re-generation.
// Generated on: 2020/03/27 12:19:05

package nl.tno.rpr.datatypes;

/** Camouflage type */
public enum CamouflageEnum32 {
  UniformPaintScheme(0),
  DesertCamouflage(1),
  WinterCamouflage(2),
  ForestCamouflage(3),
  GenericCamouflage(4);

  private final int value;

  private CamouflageEnum32(int value) {
    this.value = value;
  }

  public int getValue() {
    return value;
  }
}
