// This file was generated by the TNO Bean Generator.
// Any modifications to this file will be lost upon re-generation.
// Generated on: 2020/03/27 12:19:05

package nl.tno.rpr.datatypes;

/** Smoke chemical content */
public enum ChemicalContentEnum32 {
  Other(0),
  Hydrochloric(1),
  WhitePhosphorous(2),
  RedPhosphorous(3);

  private final int value;

  private ChemicalContentEnum32(int value) {
    this.value = value;
  }

  public int getValue() {
    return value;
  }
}
