// This file was generated by the TNO Bean Generator.
// Any modifications to this file will be lost upon re-generation.
// Generated on: 2020/03/27 12:19:05

package nl.tno.rpr.datatypes;

/** Relationship position */
public enum ConstituentPartPositionEnum16 {
  Other((short) 0),
  OnTopOf((short) 1),
  Inside((short) 2);

  private final short value;

  private ConstituentPartPositionEnum16(short value) {
    this.value = value;
  }

  public short getValue() {
    return value;
  }
}
