// This file was generated by the TNO Bean Generator.
// Any modifications to this file will be lost upon re-generation.
// Generated on: 2020/03/27 12:19:05

package nl.tno.rpr.datatypes;

/** Station name */
public enum ConstituentPartStationNameEnum16 {
  Other((short) 0),
  AircraftWingstation((short) 1),
  ShipsForwardGunmountStarboard((short) 2),
  ShipsForwardGunmountPort((short) 3),
  ShipsForwardGunmountCenterline((short) 4),
  ShipsAftGunmountStarboard((short) 5),
  ShipsAftGunmountPort((short) 6),
  ShipsAftGunmountCenterline((short) 7),
  ForwardTorpedoTube((short) 8),
  AftTorpedoTube((short) 9),
  BombBay((short) 10),
  CargoBay((short) 11),
  TruckBed((short) 12),
  TrailerBed((short) 13),
  WellDeck((short) 14),
  OnStationRangeBearing((short) 15),
  OnStationXYZ((short) 16);

  private final short value;

  private ConstituentPartStationNameEnum16(short value) {
    this.value = value;
  }

  public short getValue() {
    return value;
  }
}
