// This file was generated by the TNO Bean Generator.
// Any modifications to this file will be lost upon re-generation.
// Generated on: 2020/03/27 12:19:05

package nl.tno.rpr.datatypes;

/** Relationship nature */
public enum ConstituentPartNatureEnum16 {
  Other((short) 0),
  HostFireableMunition((short) 1),
  MunitionCarriedAsCargo((short) 2),
  FuelCarriedAsCargo((short) 3),
  GunmountAttachedToHost((short) 4),
  ComputerGeneratedForcesCarriedAsCargo((short) 5),
  VehicleCarriedAsCargo((short) 6),
  EmitterMountedOnHost((short) 7),
  MobileCommandAndControlEntityCarriedAboardHost((short) 8),
  EntityStationedWithRespectToHost((short) 9),
  TeamMemberInFormationWith((short) 10);

  private final short value;

  private ConstituentPartNatureEnum16(short value) {
    this.value = value;
  }

  public short getValue() {
    return value;
  }
}
