// This file was generated by the TNO Bean Generator.
// Any modifications to this file will be lost upon re-generation.
// Generated on: 2020/03/27 12:19:05

package nl.tno.rpr.datatypes;

/** Identifies the type of cryptographic equipment */
public enum CryptographicSystemTypeEnum16 {
  Other((short) 0),
  KY_28((short) 1),
  KY_58((short) 2),
  NarrowSpectrumSecureVoice_NSVE((short) 3),
  WideSpectrumSecureVoice_WSVE((short) 4),
  SINCGARS_ICOM((short) 5),
  KY__75((short) 6),
  KY__100((short) 7),
  KY__57((short) 8),
  KYV__5((short) 9),
  Link11KG__40A__P_NTDS_((short) 10),
  Link11BKG__40A__S((short) 11),
  Link11KG__40AR((short) 12);

  private final short value;

  private CryptographicSystemTypeEnum16(short value) {
    this.value = value;
  }

  public short getValue() {
    return value;
  }
}
