// This file was generated by the TNO Bean Generator.
// Any modifications to this file will be lost upon re-generation.
// Generated on: 2020/03/27 12:19:05

package nl.tno.rpr.datatypes;

/** Dead-reckoning algorithm */
public enum DeadReckoningAlgorithmEnum8 {
  Other((byte) 0),
  Static((byte) 1),
  DRM_FPW((byte) 2),
  DRM_RPW((byte) 3),
  DRM_RVW((byte) 4),
  DRM_FVW((byte) 5),
  DRM_FPB((byte) 6),
  DRM_RPB((byte) 7),
  DRM_RVB((byte) 8),
  DRM_FVB((byte) 9);

  private final byte value;

  private DeadReckoningAlgorithmEnum8(byte value) {
    this.value = value;
  }

  public byte getValue() {
    return value;
  }
}
