// This file was generated by the TNO Bean Generator.
// Any modifications to this file will be lost upon re-generation.
// Generated on: 2020/03/27 12:19:05

package nl.tno.rpr.datatypes;

/** Designator code name */
public enum DesignatorCodeNameEnum16 {
  Other((short) 0);

  private final short value;

  private DesignatorCodeNameEnum16(short value) {
    this.value = value;
  }

  public short getValue() {
    return value;
  }
}
