// This file was generated by the TNO Bean Generator.
// Any modifications to this file will be lost upon re-generation.
// Generated on: 2020/03/27 12:19:05

package nl.tno.rpr.datatypes;

/** Detonation result */
public enum DetonationResultCodeEnum8 {
  Other((byte) 0),
  EntityImpact((byte) 1),
  EntityProximateDetonation((byte) 2),
  GroundImpact((byte) 3),
  GroundProximateDetonation((byte) 4),
  Detonation((byte) 5),
  None((byte) 6),
  HE_hit_Small((byte) 7),
  HE_hit_Medium((byte) 8),
  HE_hit_Large((byte) 9),
  ArmorPiercingHit((byte) 10),
  DirtBlast_Small((byte) 11),
  DirtBlast_Medium((byte) 12),
  DirtBlast_Large((byte) 13),
  WaterBlast_Small((byte) 14),
  WaterBlast_Medium((byte) 15),
  WaterBlast_Large((byte) 16),
  AirHit((byte) 17),
  BuildingHit_Small((byte) 18),
  BuildingHit_Medium((byte) 19),
  BuildingHit_Large((byte) 20),
  MineClearingLineCharge((byte) 21),
  EnvironmentObjectImpact((byte) 22),
  EnvironmentObjectProximateDetonation((byte) 23),
  WaterImpact((byte) 24),
  AirBurst((byte) 25),
  Kill_with_fragment_type_1((byte) 26),
  Kill_with_fragment_type_2((byte) 27),
  Kill_with_fragment_type_3((byte) 28),
  Kill_with_fragment_type_1_after_fly__out_failure((byte) 29),
  Kill_with_fragment_type_2_after_fly__out_failure((byte) 30),
  Miss_due_to_fly__out_failure((byte) 31),
  Miss_due_to_end__game_failure((byte) 32),
  Miss_due_to_fly__out_and_end__game_failure((byte) 33);

  private final byte value;

  private DetonationResultCodeEnum8(byte value) {
    this.value = value;
  }

  public byte getValue() {
    return value;
  }
}
