// This file was generated by the TNO Bean Generator.
// Any modifications to this file will be lost upon re-generation.
// Generated on: 2020/03/27 12:19:05

package nl.tno.rpr.datatypes;

/** Emitter system function */
public enum EmitterFunctionEnum8 {
  Other((byte) 0),
  MultiFunction((byte) 1),
  EarlyWarningSurveillance((byte) 2),
  HeightFinding((byte) 3),
  FireControl((byte) 4),
  AcquisitionDetection((byte) 5),
  Tracking((byte) 6),
  GuidanceIllumination((byte) 7),
  FiringPointLaunchPointLocation((byte) 8),
  Ranging((byte) 9),
  RadarAltimeter((byte) 10),
  Imaging((byte) 11),
  MotionDetection((byte) 12),
  Navigation((byte) 13),
  Weather_Meterological((byte) 14),
  Instrumentation((byte) 15),
  Identification_Classification__including_IFF_((byte) 16),
  AAA__Anti__Aircraft_Artillery__Fire_Control((byte) 17),
  Air_Search_Bomb((byte) 18),
  Air_Intercept((byte) 19),
  Altimeter((byte) 20),
  Air_Mapping((byte) 21),
  Air_Traffic_Control((byte) 22),
  Beacon((byte) 23),
  Battlefield_Surveillance((byte) 24),
  Ground_Control_Approach((byte) 25),
  Ground_Control_Intercept((byte) 26),
  Coastal_Surveillance((byte) 27),
  Decoy_Mimic((byte) 28),
  Data_Transmission((byte) 29),
  Earth_Surveillance((byte) 30),
  Gun_Lay_Beacon((byte) 31),
  Ground_Mapping((byte) 32),
  Harbor_Surveillance((byte) 33),
  IFF_IdentifyFriendOrFoe_((byte) 34),
  ILS__Instrument_Landing_System_((byte) 35),
  Ionospheric_Sound((byte) 36),
  Interrogator((byte) 37),
  Barrage_Jamming((byte) 38),
  Click_Jamming((byte) 39),
  DeceptiveJamming((byte) 40),
  Frequency_Swept_Jamming((byte) 41),
  Jamming((byte) 42),
  NoiseJamming((byte) 43),
  Pulsed_Jamming((byte) 44),
  Repeater_Jamming((byte) 45),
  Spot_Noise_Jamming((byte) 46),
  Missile_Acquisition((byte) 47),
  Missile_Downlink((byte) 48),
  Meteorological((byte) 49),
  Space((byte) 50),
  Surface_Search((byte) 51),
  Shell_Tracking((byte) 52),
  Television((byte) 56),
  Unknown((byte) 57),
  Video_Remoting((byte) 58),
  Experimental_or_Training((byte) 59),
  Missile_Guidance((byte) 60),
  Missile_Homing((byte) 61),
  Missile_Tracking((byte) 62),
  JammingNoise((byte) 64),
  JammingDeception((byte) 65),
  Decoy((byte) 66),
  Navigation_Distance_Measuring_Equipment((byte) 71),
  Terrain_Following((byte) 72),
  Weather_Avoidance((byte) 73),
  Proximity_Fuse((byte) 74),
  Instrumentation_deprecated_((byte) 75),
  Radiosonde((byte) 76),
  Sonobuoy((byte) 77),
  BathythermalSensor((byte) 78),
  TowedCounterMeasure((byte) 79),
  WeaponNonLethal((byte) 96),
  WeaponLethal((byte) 97);

  private final byte value;

  private EmitterFunctionEnum8(byte value) {
    this.value = value;
  }

  public byte getValue() {
    return value;
  }
}
