// This file was generated by the TNO Bean Generator.
// Any modifications to this file will be lost upon re-generation.
// Generated on: 2020/03/27 12:19:05

package nl.tno.rpr.datatypes;

/** Radio signal encoding type */
public enum EncodingTypeEnum32 {
  Encoding_8__bit_mu__law(1),
  CVSD_per_MIL__STD__188__113(2),
  ADPCM_per_CCITT_G721(3),
  Encoding_16__bit_linear_PCM(4),
  Encoding_8__bit_linear_PCM(5),
  VQ__Vector_Quantization_(6),
  _unavailableForUse_(7),
  GSMFull__Rate_ETSI06_10_(8),
  GSMHalf__Rate_ETSI06_20_(9),
  SpeexNarrowBand(10),
  Encoding_16__bitLinearPCM2_sComplement_LittleEndian(100),
  _unavailableForUse2_(255);

  private final int value;

  private EncodingTypeEnum32(int value) {
    this.value = value;
  }

  public int getValue() {
    return value;
  }
}
