// This file was generated by the TNO Bean Generator.
// Any modifications to this file will be lost upon re-generation.
// Generated on: 2020/03/27 12:19:05

package nl.tno.rpr.datatypes;

/** Environment data coordinate system */
public enum EnvironmentDataCoordinateSystemEnum16 {
  RightHandedCartesian_localTopographicProjection_East_North_Up_((short) 0),
  LeftHandedCartesian_localTopographicProjection_East_North_Down_((short) 1),
  Latitude_Longitude_Height((short) 2),
  Latitude_Longitude_Depth((short) 3);

  private final short value;

  private EnvironmentDataCoordinateSystemEnum16(short value) {
    this.value = value;
  }

  public short getValue() {
    return value;
  }
}
