// This file was generated by the TNO Bean Generator.
// Any modifications to this file will be lost upon re-generation.
// Generated on: 2020/03/27 12:19:05

package nl.tno.rpr.datatypes;

/** Environment process model type */
public enum EnvironmentModelTypeEnum8 {
  EnvironmentModelUnknown((byte) 0);

  private final byte value;

  private EnvironmentModelTypeEnum8(byte value) {
    this.value = value;
  }

  public byte getValue() {
    return value;
  }
}
