// This file was generated by the TNO Bean Generator.
// Any modifications to this file will be lost upon re-generation.
// Generated on: 2020/03/27 12:19:05

package nl.tno.rpr.datatypes;

/** Record specifying an environment (geometry or state) record */
public class EnvironmentRecStruct {

  /** Identifies the sequentially numbered record index */
  int Index;

  /** Specifies geometry and state record alternatives */
  EnvironmentRecVariantStruct DataVariant;

  public int getIndex() {
    return this.Index;
  }

  public void setIndex(int Index) {
    this.Index = Index;
  }

  public EnvironmentRecVariantStruct getDataVariant() {
    return this.DataVariant;
  }

  public void setDataVariant(EnvironmentRecVariantStruct DataVariant) {
    this.DataVariant = DataVariant;
  }
}
