// This file was generated by the TNO Bean Generator.
// Any modifications to this file will be lost upon re-generation.
// Generated on: 2020/03/27 12:19:05

package nl.tno.rpr.datatypes;

/** Grid axis type */
public enum EnvironmentGridAxisTypeEnum8 {
  RegularGridAxisType((byte) 0),
  IrregularGridAxisType((byte) 1);

  private final byte value;

  private EnvironmentGridAxisTypeEnum8(byte value) {
    this.value = value;
  }

  public byte getValue() {
    return value;
  }
}
