// This file was generated by the TNO Bean Generator.
// Any modifications to this file will be lost upon re-generation.
// Generated on: 2020/03/27 12:19:05

package nl.tno.rpr.datatypes;

/** Environment data grid type */
public enum EnvironmentGridTypeEnum8 {
  ConstantGrid((byte) 0),
  UpdatedGrid((byte) 1);

  private final byte value;

  private EnvironmentGridTypeEnum8(byte value) {
    this.value = value;
  }

  public byte getValue() {
    return value;
  }
}
