// This file was generated by the TNO Bean Generator.
// Any modifications to this file will be lost upon re-generation.
// Generated on: 2020/03/27 12:19:05

package nl.tno.rpr.datatypes;

/** Environment data representation type */
public enum EnvironmentDataRepresentationEnum16 {
  EnvironmentDataType0((short) 0),
  EnvironmentDataType1((short) 1),
  EnvironmentDataType2((short) 2);

  private final short value;

  private EnvironmentDataRepresentationEnum16(short value) {
    this.value = value;
  }

  public short getValue() {
    return value;
  }
}
