// This file was generated by the TNO Bean Generator.
// Any modifications to this file will be lost upon re-generation.
// Generated on: 2020/03/27 12:19:05

package nl.tno.rpr.datatypes;

/** Event type */
public enum EventTypeEnum32 {
  Other(0),
  RanOutOfAmmunition(2),
  KilledInAction(3),
  Damage(4),
  MobilityDisabled(5),
  FireDisabled(6),
  RanOutOfFuel(7),
  EntityInitialization(8),
  RequestForIndirectFireOrCASMission(9),
  IndirectFireOrCASMission(10),
  MinefieldEntry(11),
  MinefieldDetonation(12),
  VehicleMasterPowerOn(13),
  VehicleMasterPowerOff(14),
  AggregateStateChangeRequested(15),
  PreventCollision_Detonation(16),
  OwnershipReport(17);

  private final int value;

  private EventTypeEnum32(int value) {
    this.value = value;
  }

  public int getValue() {
    return value;
  }
}
