// This file was generated by the TNO Bean Generator.
// Any modifications to this file will be lost upon re-generation.
// Generated on: 2020/03/27 12:19:05

package nl.tno.rpr.datatypes;

/** Force ID */
public enum ForceIdentifierEnum8 {
  Other((byte) 0),
  Friendly((byte) 1),
  Opposing((byte) 2),
  Neutral((byte) 3),
  Friendly_2((byte) 4),
  Opposing_2((byte) 5),
  Neutral_2((byte) 6),
  Friendly_3((byte) 7),
  Opposing_3((byte) 8),
  Neutral_3((byte) 9),
  Friendly_4((byte) 10),
  Opposing_4((byte) 11),
  Neutral_4((byte) 12),
  Friendly_5((byte) 13),
  Opposing_5((byte) 14),
  Neutral_5((byte) 15),
  Friendly_6((byte) 16),
  Opposing_6((byte) 17),
  Neutral_6((byte) 18),
  Friendly_7((byte) 19),
  Opposing_7((byte) 20),
  Neutral_7((byte) 21),
  Friendly_8((byte) 22),
  Opposing_8((byte) 23),
  Neutral_8((byte) 24),
  Friendly_9((byte) 25),
  Opposing_9((byte) 26),
  Neutral_9((byte) 27),
  Friendly_10((byte) 28),
  Opposing_10((byte) 29),
  Neutral_10((byte) 30);

  private final byte value;

  private ForceIdentifierEnum8(byte value) {
    this.value = value;
  }

  public byte getValue() {
    return value;
  }
}
