// This file was generated by the TNO Bean Generator.
// Any modifications to this file will be lost upon re-generation.
// Generated on: 2020/03/27 12:19:05

package nl.tno.rpr.datatypes;

/** Formation */
public enum FormationEnum32 {
  Other(0),
  Assembly(1),
  Vee(2),
  Wedge(3),
  Line(4),
  Column(5);

  private final int value;

  private FormationEnum32(int value) {
    this.value = value;
  }

  public int getValue() {
    return value;
  }
}
