// This file was generated by the TNO Bean Generator.
// Any modifications to this file will be lost upon re-generation.
// Generated on: 2020/03/27 12:19:05

package nl.tno.rpr.datatypes;

/** Record specifying grid Xi axis data */
public class GridAxisStruct {

  /** Specifies the coordinate of the origin (or initial value) for the Xi axis */
  double InitialValue;

  /** Specifies the coordinate of the endpoint (or final value) for the Xi axis */
  double FinalValue;

  /** Specifies the total number of grid points along the Xi domain axis */
  short TotalNumberOfPoints;

  /**
   * Specifies the integer valued interleaf factor along a domain (grid) Xi axis ; a value of one
   * shall indicate no sub-sampling (interleaving), while integer values greater than one shall
   * indicate the sampling frequency along an axis
   */
  byte InterleafFactor;

  /** Specifies the number of grid locations along the Xi axis */
  short NumberOfPoints;

  /** Specifies the index of the initial grid point along the Xi domain axis */
  short InitialIndex;

  /** Specifies axis data alternatives */
  GridAxisTypeVariantStruct AxisType__A__Alternatives;

  public double getInitialValue() {
    return this.InitialValue;
  }

  public void setInitialValue(double InitialValue) {
    this.InitialValue = InitialValue;
  }

  public double getFinalValue() {
    return this.FinalValue;
  }

  public void setFinalValue(double FinalValue) {
    this.FinalValue = FinalValue;
  }

  public short getTotalNumberOfPoints() {
    return this.TotalNumberOfPoints;
  }

  public void setTotalNumberOfPoints(short TotalNumberOfPoints) {
    this.TotalNumberOfPoints = TotalNumberOfPoints;
  }

  public byte getInterleafFactor() {
    return this.InterleafFactor;
  }

  public void setInterleafFactor(byte InterleafFactor) {
    this.InterleafFactor = InterleafFactor;
  }

  public short getNumberOfPoints() {
    return this.NumberOfPoints;
  }

  public void setNumberOfPoints(short NumberOfPoints) {
    this.NumberOfPoints = NumberOfPoints;
  }

  public short getInitialIndex() {
    return this.InitialIndex;
  }

  public void setInitialIndex(short InitialIndex) {
    this.InitialIndex = InitialIndex;
  }

  public GridAxisTypeVariantStruct getAxisType__A__Alternatives() {
    return this.AxisType__A__Alternatives;
  }

  public void setAxisType__A__Alternatives(GridAxisTypeVariantStruct AxisType__A__Alternatives) {
    this.AxisType__A__Alternatives = AxisType__A__Alternatives;
  }
}
