// This file was generated by the TNO Bean Generator.
// Any modifications to this file will be lost upon re-generation.
// Generated on: 2020/03/27 12:19:05

package nl.tno.rpr.datatypes;

/** Record specifying type 0 data representation */
public class GridValueType0Struct {

  /** Specifies the number of bytes */
  byte[] NumberOfBytes__A__Values;

  /** Brings the record length to a 32-bit boundary */
  byte[] PaddingTo32;

  public byte[] getNumberOfBytes__A__Values() {
    return this.NumberOfBytes__A__Values;
  }

  public void setNumberOfBytes__A__Values(byte[] NumberOfBytes__A__Values) {
    this.NumberOfBytes__A__Values = NumberOfBytes__A__Values;
  }

  public byte[] getPaddingTo32() {
    return this.PaddingTo32;
  }

  public void setPaddingTo32(byte[] PaddingTo32) {
    this.PaddingTo32 = PaddingTo32;
  }
}
