// This file was generated by the TNO Bean Generator.
// Any modifications to this file will be lost upon re-generation.
// Generated on: 2020/03/27 12:19:05

package nl.tno.rpr.datatypes;

/** Record specifying type 1 data representation */
public class GridValueType1Struct {

  /**
   * Specifies the constant scale factor used to scale the environmental state variable data values
   */
  float Scale;

  /** Specifies the constant offset used to scale the environmental state variable data values */
  float Offset;

  /** Specifies the number of environmental state variable data values */
  short[] NumberOfValues__A__Values;

  /** Brings the record length to a 32-bit boundary */
  byte[] PaddingTo32;

  public float getScale() {
    return this.Scale;
  }

  public void setScale(float Scale) {
    this.Scale = Scale;
  }

  public float getOffset() {
    return this.Offset;
  }

  public void setOffset(float Offset) {
    this.Offset = Offset;
  }

  public short[] getNumberOfValues__A__Values() {
    return this.NumberOfValues__A__Values;
  }

  public void setNumberOfValues__A__Values(short[] NumberOfValues__A__Values) {
    this.NumberOfValues__A__Values = NumberOfValues__A__Values;
  }

  public byte[] getPaddingTo32() {
    return this.PaddingTo32;
  }

  public void setPaddingTo32(byte[] PaddingTo32) {
    this.PaddingTo32 = PaddingTo32;
  }
}
