// This file was generated by the TNO Bean Generator.
// Any modifications to this file will be lost upon re-generation.
// Generated on: 2020/03/27 12:19:05

package nl.tno.rpr.datatypes;

/** Record specifying type 2 data representation */
public class GridValueType2Struct {

  /** Specifies the number of environmental state variable data values */
  float[] NumberOfValues__A__Values;

  public float[] getNumberOfValues__A__Values() {
    return this.NumberOfValues__A__Values;
  }

  public void setNumberOfValues__A__Values(float[] NumberOfValues__A__Values) {
    this.NumberOfValues__A__Values = NumberOfValues__A__Values;
  }
}
