// This file was generated by the TNO Bean Generator.
// Any modifications to this file will be lost upon re-generation.
// Generated on: 2020/03/27 12:19:05

package nl.tno.rpr.datatypes;

/** Hatch state */
public enum HatchStateEnum32 {
  NotApplicable(0),
  PrimaryHatchIsClosed(1),
  PrimaryHatchIsPopped(2),
  PrimaryHatchIsPoppedAndPersonIsVisibleUnderHatch(3),
  PrimaryHatchIsOpen(4),
  PrimaryHatchIsOpenAndPersonIsVisible(5);

  private final int value;

  private HatchStateEnum32(int value) {
    this.value = value;
  }

  public int getValue() {
    return value;
  }
}
