// This file was generated by the TNO Bean Generator.
// Any modifications to this file will be lost upon re-generation.
// Generated on: 2020/03/27 12:19:05

package nl.tno.rpr.datatypes;

/** IFF operational parameter 2 */
public enum IffOperationalParameter2Enum8 {
  Other((byte) 0);

  private final byte value;

  private IffOperationalParameter2Enum8(byte value) {
    this.value = value;
  }

  public byte getValue() {
    return value;
  }
}
