// This file was generated by the TNO Bean Generator.
// Any modifications to this file will be lost upon re-generation.
// Generated on: 2020/03/27 12:19:05

package nl.tno.rpr.datatypes;

/** IFF system mode */
public enum IffSystemModeEnum8 {
  NoStatement((byte) 0),
  Off((byte) 1),
  Standby((byte) 2),
  Normal((byte) 3),
  Emergency((byte) 4),
  LowOrLowSensitivity((byte) 5);

  private final byte value;

  private IffSystemModeEnum8(byte value) {
    this.value = value;
  }

  public byte getValue() {
    return value;
  }
}
