// This file was generated by the TNO Bean Generator.
// Any modifications to this file will be lost upon re-generation.
// Generated on: 2020/03/27 12:19:05

package nl.tno.rpr.datatypes;

/** IFF system type */
public enum IffSystemTypeEnum16 {
  Other((short) 0),
  MarkTransponder((short) 1),
  MarkInterrogator((short) 2),
  SovietTransponder((short) 3),
  SovietInterrogator((short) 4),
  RRBTransponder((short) 5),
  MarkXIIAInterrogator((short) 6),
  Mode5Interrogator((short) 7),
  ModeSInterrogator((short) 8),
  MarkXIIATransponder((short) 9),
  Mode5Transponder((short) 10),
  ModeSTransponder((short) 11),
  MarkXIIACombinedInterrogator_Transponder_CIT_((short) 12),
  MarkXIICombinedInterrogator_Transponder_CIT_((short) 13),
  TCAS_ACASTransceiver((short) 14);

  private final short value;

  private IffSystemTypeEnum16(short value) {
    this.value = value;
  }

  public short getValue() {
    return value;
  }
}
