// This file was generated by the TNO Bean Generator.
// Any modifications to this file will be lost upon re-generation.
// Generated on: 2020/03/27 12:19:05

package nl.tno.rpr.datatypes;

/** Major classification of the modulation type. */
public enum MajorRFModulationTypeEnum16 {
  Other((short) 0),
  Amplitude((short) 1),
  AmplitudeAndAngle((short) 2),
  Angle((short) 3),
  Combination((short) 4),
  Pulse((short) 5),
  Unmodulated((short) 6),
  CarrierPhaseShiftModulation_CPSM_((short) 7);

  private final short value;

  private MajorRFModulationTypeEnum16(short value) {
    this.value = value;
  }

  public short getValue() {
    return value;
  }
}
