// This file was generated by the TNO Bean Generator.
// Any modifications to this file will be lost upon re-generation.
// Generated on: 2020/03/27 12:19:05

package nl.tno.rpr.datatypes;

/** Marking character set */
public enum MarkingEncodingEnum8 {
  Other((byte) 0),
  ASCII((byte) 1),
  ArmyMarkingCCTT((byte) 2),
  DigitChevron((byte) 3);

  private final byte value;

  private MarkingEncodingEnum8(byte value) {
    this.value = value;
  }

  public byte getValue() {
    return value;
  }
}
