// This file was generated by the TNO Bean Generator.
// Any modifications to this file will be lost upon re-generation.
// Generated on: 2020/03/27 12:19:05

package nl.tno.rpr.datatypes;

/** Minefield sensor type */
public enum MinefieldSensorTypeEnum32 {
  Other(0),
  UnaidedEyeActivelySearching(4096),
  UnaidedEyeNotActivelySearching(4097),
  Binoculars(4098),
  ImageIntensifier(4099),
  HMMWVOccupantActivelySearching(4100),
  HMMWVOccupantNotActivelySearching(4101),
  TruckOccupantActivelySearching(4102),
  TruckOccupantNotActivelySearching(4103),
  TrackedVehicleOccupantClosedHatchActivelySearching(4104),
  TrackedVehicleOccupantClosedHatchNotActivelySearching(4105),
  TrackedVehicleOccupantOpenHatchActivelySearching(4106),
  TrackedVehicleOccupantOpenHatchNotActivelySearching(4107),
  FLIR_Generic3_5(8192),
  FLIR_Generic8_12(8193),
  FLIR_ASTAMIDS_I(8194),
  FLIR_ASTAMIDS_II(8195),
  FLIR_GSTAMIDS3_5(8196),
  FLIR_GSTAMIDS8_12(8197),
  FLIR_HSTAMIDS3_5(8198),
  FLIR_HSTAMIDS8_12(8199),
  FLIR_COBRA3_5(8200),
  FLIR_COBRA8_12(8201),
  RADAR_Generic(12288),
  RADAR_Generic_GPR(12289),
  RADAR_GSTAMIDS_I(12290),
  RADAR_GSTAMIDS_II(12291),
  RADAR_HSTAMIDS_I(12292),
  RADAR_HSTAMIDS_II(12293),
  Magnetic_Generic(16384),
  Magnetic_ANPSS_11(16385),
  Magnetic_ANPSS_12(16386),
  Magnetic_GSTAMIDS(16389),
  Laser_Generic(20480),
  Laser_ASTAMIDS(20481),
  SONAR_Generic(24576),
  Physical_GenericProbe(28672),
  Physical_ProbeMetalContent(28673),
  Physical_ProbeNoMetalContent(28674),
  Multispectral_Generic(32768);

  private final int value;

  private MinefieldSensorTypeEnum32(int value) {
    this.value = value;
  }

  public int getValue() {
    return value;
  }
}
