// This file was generated by the TNO Bean Generator.
// Any modifications to this file will be lost upon re-generation.
// Generated on: 2020/03/27 12:19:05

package nl.tno.rpr.datatypes;

/** Record specifying a minefield lane marker segment */
public class MinefieldLaneMarkerStruct {

  /** Specifies the minefield lane marker segment characteristics */
  LinearSegmentStruct SegmentParameters;

  /** Specifies the visible side(s) of the minefield lane marker segment */
  VisibleSideLocationEnum32 VisibleSideLocation;

  public LinearSegmentStruct getSegmentParameters() {
    return this.SegmentParameters;
  }

  public void setSegmentParameters(LinearSegmentStruct SegmentParameters) {
    this.SegmentParameters = SegmentParameters;
  }

  public VisibleSideLocationEnum32 getVisibleSideLocation() {
    return this.VisibleSideLocation;
  }

  public void setVisibleSideLocation(VisibleSideLocationEnum32 VisibleSideLocation) {
    this.VisibleSideLocation = VisibleSideLocation;
  }
}
