// This file was generated by the TNO Bean Generator.
// Any modifications to this file will be lost upon re-generation.
// Generated on: 2020/03/27 12:19:05

package nl.tno.rpr.datatypes;

/** Minefield status */
public enum MinefieldStatusEnum8 {
  Active((byte) 0),
  Inactive((byte) 1);

  private final byte value;

  private MinefieldStatusEnum8(byte value) {
    this.value = value;
  }

  public byte getValue() {
    return value;
  }
}
