// This file was generated by the TNO Bean Generator.
// Any modifications to this file will be lost upon re-generation.
// Generated on: 2020/03/27 12:19:05

package nl.tno.rpr.datatypes;

/** Minefield fuse type */
public enum MinefieldFusingEnum32 {
  NoFuse(0),
  Other(1),
  Pressure(2),
  Magnetic(3),
  TiltRod(4),
  Command(5),
  TripWire(6);

  private final int value;

  private MinefieldFusingEnum32(int value) {
    this.value = value;
  }

  public int getValue() {
    return value;
  }
}
