// This file was generated by the TNO Bean Generator.
// Any modifications to this file will be lost upon re-generation.
// Generated on: 2020/03/27 12:19:05

package nl.tno.rpr.datatypes;

/** Minefield type */
public enum MinefieldTypeEnum8 {
  MixedAntiPersonnelAntiTank((byte) 0),
  PureAntiPersonnel((byte) 1),
  PureAntiTank((byte) 2);

  private final byte value;

  private MinefieldTypeEnum8(byte value) {
    this.value = value;
  }

  public byte getValue() {
    return value;
  }
}
