// This file was generated by the TNO Bean Generator.
// Any modifications to this file will be lost upon re-generation.
// Generated on: 2020/03/27 12:19:05

package nl.tno.rpr.datatypes;

/** Minefield paint scheme */
public enum MinefieldPaintSchemeEnum32 {
  Other(0),
  Standard(1),
  CamouflageDesert(2),
  CamouflageJungle(3),
  CamouflageSnow(4),
  CamouflageGravel(5),
  CamouflagePavement(6),
  CamouflageSand(7),
  NaturalWood(8),
  Clear(9),
  Red(10),
  Blue(11),
  Green(12),
  Olive(13),
  White(14),
  Tan(15),
  Black(16),
  Yellow(17),
  Brown(18);

  private final int value;

  private MinefieldPaintSchemeEnum32(int value) {
    this.value = value;
  }

  public int getValue() {
    return value;
  }
}
