// This file was generated by the TNO Bean Generator.
// Any modifications to this file will be lost upon re-generation.
// Generated on: 2020/03/27 12:19:05

package nl.tno.rpr.datatypes;

/** Minefield lane status */
public enum MinefieldLaneEnum8 {
  MinefieldHasActiveLane((byte) 0),
  MinefieldHasAnInactiveLane((byte) 1);

  private final byte value;

  private MinefieldLaneEnum8(byte value) {
    this.value = value;
  }

  public byte getValue() {
    return value;
  }
}
