// This file was generated by the TNO Bean Generator.
// Any modifications to this file will be lost upon re-generation.
// Generated on: 2020/03/27 12:19:05

package nl.tno.rpr.datatypes;

/** Density of environmentals */
public enum OpacityCodeEnum32 {
  Clear(0),
  Hazy(1),
  Dense(2),
  VeryDense(3),
  Opaque(4);

  private final int value;

  private OpacityCodeEnum32(int value) {
    this.value = value;
  }

  public int getValue() {
    return value;
  }
}
