// This file was generated by the TNO Bean Generator.
// Any modifications to this file will be lost upon re-generation.
// Generated on: 2020/03/27 12:19:05

package nl.tno.rpr.datatypes;

/**
 * Variant record specifying the type of articulation parameter (articulated or attached part), and
 * its type and value.
 */
public class ParameterValueVariantStruct {

  /** Discriminant */
  ParameterTypeEnum32 ArticulatedParameterType;

  /** Alternative for an articulated part. */
  ArticulatedPartsStruct ArticulatedParts;

  /** Alternative for an attached part. */
  AttachedPartsStruct AttachedParts;

  public ParameterTypeEnum32 getArticulatedParameterType() {
    return this.ArticulatedParameterType;
  }

  public void setArticulatedParameterType(ParameterTypeEnum32 ArticulatedParameterType) {
    this.ArticulatedParameterType = ArticulatedParameterType;
  }

  public ArticulatedPartsStruct getArticulatedParts() {
    return this.ArticulatedParts;
  }

  public void setArticulatedParts(ArticulatedPartsStruct ArticulatedParts) {
    this.ArticulatedParts = ArticulatedParts;
  }

  public AttachedPartsStruct getAttachedParts() {
    return this.AttachedParts;
  }

  public void setAttachedParts(AttachedPartsStruct AttachedParts) {
    this.AttachedParts = AttachedParts;
  }
}
