// This file was generated by the TNO Bean Generator.
// Any modifications to this file will be lost upon re-generation.
// Generated on: 2020/03/27 12:19:05

package nl.tno.rpr.datatypes;

/** Record specifying the location of a perimeter point */
public class PerimeterPointStruct {

  /** Specifies the X coordinate */
  float X;

  /** Specifies the Y coordinate */
  float Y;

  public float getX() {
    return this.X;
  }

  public void setX(float X) {
    this.X = X;
  }

  public float getY() {
    return this.Y;
  }

  public void setY(float Y) {
    this.Y = Y;
  }
}
