// This file was generated by the TNO Bean Generator.
// Any modifications to this file will be lost upon re-generation.
// Generated on: 2020/03/27 12:19:05

package nl.tno.rpr.datatypes;

/** Record specifying plume dimensions */
public class PlumeDimensionStruct {

  /** Plume length */
  float Length;

  /** Plume width */
  float Width;

  /** Plume height */
  float Height;

  public float getLength() {
    return this.Length;
  }

  public void setLength(float Length) {
    this.Length = Length;
  }

  public float getWidth() {
    return this.Width;
  }

  public void setWidth(float Width) {
    this.Width = Width;
  }

  public float getHeight() {
    return this.Height;
  }

  public void setHeight(float Height) {
    this.Height = Height;
  }
}
