// This file was generated by the TNO Bean Generator.
// Any modifications to this file will be lost upon re-generation.
// Generated on: 2020/03/27 12:19:05

package nl.tno.rpr.datatypes;

/** Propulsion plant configuration */
public enum PropulsionPlantEnum8 {
  Other((byte) 0),
  Diesel_Electric((byte) 1),
  Diesel((byte) 2),
  Battery((byte) 3),
  TurbineReduction((byte) 4),
  Steam((byte) 6),
  GasTurbine((byte) 7);

  private final byte value;

  private PropulsionPlantEnum8(byte value) {
    this.value = value;
  }

  public byte getValue() {
    return value;
  }
}
