// This file was generated by the TNO Bean Generator.
// Any modifications to this file will be lost upon re-generation.
// Generated on: 2020/03/27 12:19:05

package nl.tno.rpr.datatypes;

/** Detailed modulation types for Pulse Modulation */
public enum PulseModulationTypeEnum16 {
  Other((short) 0),
  Pulse((short) 1),
  XBandTACANPulse((short) 2),
  YBandTACANPulse((short) 3);

  private final short value;

  private PulseModulationTypeEnum16(short value) {
    this.value = value;
  }

  public short getValue() {
    return value;
  }
}
