// This file was generated by the TNO Bean Generator.
// Any modifications to this file will be lost upon re-generation.
// Generated on: 2020/03/27 12:19:05

package nl.tno.rpr.datatypes;

/** The operational state of a radio receiver. */
public enum ReceiverOperationalStatusEnum16 {
  Off((short) 0),
  OnButNotReceiving((short) 1),
  OnAndReceiving((short) 2);

  private final short value;

  private ReceiverOperationalStatusEnum16(short value) {
    this.value = value;
  }

  public short getValue() {
    return value;
  }
}
