// This file was generated by the TNO Bean Generator.
// Any modifications to this file will be lost upon re-generation.
// Generated on: 2020/03/27 12:19:05

package nl.tno.rpr.datatypes;

/** Record data. */
public class RecordStruct {

  /** Number of bits of data. */
  int NumberOfBits;

  /** Data. */
  byte[] NumberOfBytes__A__RecordData;

  /** Brings the record length to a 32-bit boundary */
  byte[] PaddingTo32;

  public int getNumberOfBits() {
    return this.NumberOfBits;
  }

  public void setNumberOfBits(int NumberOfBits) {
    this.NumberOfBits = NumberOfBits;
  }

  public byte[] getNumberOfBytes__A__RecordData() {
    return this.NumberOfBytes__A__RecordData;
  }

  public void setNumberOfBytes__A__RecordData(byte[] NumberOfBytes__A__RecordData) {
    this.NumberOfBytes__A__RecordData = NumberOfBytes__A__RecordData;
  }

  public byte[] getPaddingTo32() {
    return this.PaddingTo32;
  }

  public void setPaddingTo32(byte[] PaddingTo32) {
    this.PaddingTo32 = PaddingTo32;
  }
}
