// This file was generated by the TNO Bean Generator.
// Any modifications to this file will be lost upon re-generation.
// Generated on: 2020/03/27 12:19:05

package nl.tno.rpr.datatypes;

/** A set of records and record details. */
public class RecordSetStruct {

  /**
   * This field shall specify the data structure used to convey the parameter values of the record
   * for each record.
   */
  DatumIdentifierEnum32 RecordSetIdentifier;

  /** This field shall specify the serial number of the first record in the array. */
  int RecordSetSerialNumber;

  /** This field contains the records of the format specified by the Record ID field. */
  RecordStruct[] NumberOfRecords__A__RecordValues;

  public DatumIdentifierEnum32 getRecordSetIdentifier() {
    return this.RecordSetIdentifier;
  }

  public void setRecordSetIdentifier(DatumIdentifierEnum32 RecordSetIdentifier) {
    this.RecordSetIdentifier = RecordSetIdentifier;
  }

  public int getRecordSetSerialNumber() {
    return this.RecordSetSerialNumber;
  }

  public void setRecordSetSerialNumber(int RecordSetSerialNumber) {
    this.RecordSetSerialNumber = RecordSetSerialNumber;
  }

  public RecordStruct[] getNumberOfRecords__A__RecordValues() {
    return this.NumberOfRecords__A__RecordValues;
  }

  public void setNumberOfRecords__A__RecordValues(RecordStruct[] NumberOfRecords__A__RecordValues) {
    this.NumberOfRecords__A__RecordValues = NumberOfRecords__A__RecordValues;
  }
}
