// This file was generated by the TNO Bean Generator.
// Any modifications to this file will be lost upon re-generation.
// Generated on: 2020/03/27 12:19:05

package nl.tno.rpr.datatypes;

/** Record specifying Rectangular Volume 1 geometry record */
public class RectVol1GeomRecStruct {

  /** Corner location X, Y, Z */
  WorldLocationStruct CornerLocation;

  /** Dimensions */
  DimensionStruct Dimensions;

  /** Orientation, specified by Euler angles */
  OrientationStruct Orientation;

  public WorldLocationStruct getCornerLocation() {
    return this.CornerLocation;
  }

  public void setCornerLocation(WorldLocationStruct CornerLocation) {
    this.CornerLocation = CornerLocation;
  }

  public DimensionStruct getDimensions() {
    return this.Dimensions;
  }

  public void setDimensions(DimensionStruct Dimensions) {
    this.Dimensions = Dimensions;
  }

  public OrientationStruct getOrientation() {
    return this.Orientation;
  }

  public void setOrientation(OrientationStruct Orientation) {
    this.Orientation = Orientation;
  }
}
