// This file was generated by the TNO Bean Generator.
// Any modifications to this file will be lost upon re-generation.
// Generated on: 2020/03/27 12:19:05

package nl.tno.rpr.datatypes;

/** The reference coordinate system used */
public enum ReferenceSystemEnum8 {
  WorldCoordinates((byte) 1),
  EntityCoordinates((byte) 2);

  private final byte value;

  private ReferenceSystemEnum8(byte value) {
    this.value = value;
  }

  public byte getValue() {
    return value;
  }
}
