// This file was generated by the TNO Bean Generator.
// Any modifications to this file will be lost upon re-generation.
// Generated on: 2020/03/27 12:19:05

package nl.tno.rpr.datatypes;

/** Relative position in right-handed Cartesian coordinates. */
public class RelativePositionStruct {

  /** The distance from the reference location along the X axis. */
  float BodyXDistance;

  /** The distance from the reference location along the Y axis. */
  float BodyYDistance;

  /** The distance from the reference location along the Z axis. */
  float BodyZDistance;

  public float getBodyXDistance() {
    return this.BodyXDistance;
  }

  public void setBodyXDistance(float BodyXDistance) {
    this.BodyXDistance = BodyXDistance;
  }

  public float getBodyYDistance() {
    return this.BodyYDistance;
  }

  public void setBodyYDistance(float BodyYDistance) {
    this.BodyYDistance = BodyYDistance;
  }

  public float getBodyZDistance() {
    return this.BodyZDistance;
  }

  public void setBodyZDistance(float BodyZDistance) {
    this.BodyZDistance = BodyZDistance;
  }
}
