// This file was generated by the TNO Bean Generator.
// Any modifications to this file will be lost upon re-generation.
// Generated on: 2020/03/27 12:19:05

package nl.tno.rpr.datatypes;

/** Relative position in polar coordinates. */
public class RelativeRangeBearingStruct {

  /** The range from the reference location. */
  float Range;

  /** The bearing from the reference location. */
  float Bearing;

  public float getRange() {
    return this.Range;
  }

  public void setRange(float Range) {
    this.Range = Range;
  }

  public float getBearing() {
    return this.Bearing;
  }

  public void setBearing(float Bearing) {
    this.Bearing = Bearing;
  }
}
