// This file was generated by the TNO Bean Generator.
// Any modifications to this file will be lost upon re-generation.
// Generated on: 2020/03/27 12:19:05

package nl.tno.rpr.datatypes;

/** Result of repair */
public enum RepairResultEnum8 {
  Other((byte) 0),
  RepairEnded((byte) 1),
  InvalidRepair((byte) 2),
  RepairInterrupted((byte) 3),
  ServiceCanceledByTheSupplier((byte) 4);

  private final byte value;

  private RepairResultEnum8(byte value) {
    this.value = value;
  }

  public byte getValue() {
    return value;
  }
}
