// This file was generated by the TNO Bean Generator.
// Any modifications to this file will be lost upon re-generation.
// Generated on: 2020/03/27 12:19:05

package nl.tno.rpr.datatypes;

/** Response flag */
public enum ResponseFlagEnum16 {
  Other((short) 0),
  AbleToComply((short) 1),
  UnableToComply((short) 2),
  PendingOperatorAction((short) 3);

  private final short value;

  private ResponseFlagEnum16(short value) {
    this.value = value;
  }

  public short getValue() {
    return value;
  }
}
