// This file was generated by the TNO Bean Generator.
// Any modifications to this file will be lost upon re-generation.
// Generated on: 2020/03/27 12:19:05

package nl.tno.rpr.datatypes;

/** The radio system type associated with this transmitter. */
public enum RFModulationSystemTypeEnum16 {
  Other((short) 0),
  Generic((short) 1),
  HQ((short) 2),
  HQII((short) 3),
  HQIIA((short) 4),
  SINCGARS((short) 5),
  CCTT_SINCGARS((short) 6),
  EPLRS_EnhancedPositionLocationReportingSystem_((short) 7),
  JTIDS_MIDS((short) 8),
  Link11((short) 9),
  Link11B((short) 10),
  L__BandSATCOM((short) 11),
  EnhancedSINCGARS7_3((short) 12),
  NavigationAid((short) 13);

  private final short value;

  private RFModulationSystemTypeEnum16(short value) {
    this.value = value;
  }

  public short getValue() {
    return value;
  }
}
