// This file was generated by the TNO Bean Generator.
// Any modifications to this file will be lost upon re-generation.
// Generated on: 2020/03/27 12:19:05

package nl.tno.rpr.datatypes;

/** Service type */
public enum ServiceTypeEnum8 {
  Other((byte) 0),
  Resupply((byte) 1),
  Repair((byte) 2);

  private final byte value;

  private ServiceTypeEnum8(byte value) {
    this.value = value;
  }

  public byte getValue() {
    return value;
  }
}
