// This file was generated by the TNO Bean Generator.
// Any modifications to this file will be lost upon re-generation.
// Generated on: 2020/03/27 12:19:05

package nl.tno.rpr.datatypes;

/** Identifies the actual spread spectrum technique in use. */
public class SpreadSpectrumVariantStruct {

  /** Discriminant */
  SpreadSpectrumEnum16 SpreadSpectrumType;

  /** Modulation parameters for SINCGARS radio system. */
  SINCGARSModulationStruct SINCGARSModulation;

  public SpreadSpectrumEnum16 getSpreadSpectrumType() {
    return this.SpreadSpectrumType;
  }

  public void setSpreadSpectrumType(SpreadSpectrumEnum16 SpreadSpectrumType) {
    this.SpreadSpectrumType = SpreadSpectrumType;
  }

  public SINCGARSModulationStruct getSINCGARSModulation() {
    return this.SINCGARSModulation;
  }

  public void setSINCGARSModulation(SINCGARSModulationStruct SINCGARSModulation) {
    this.SINCGARSModulation = SINCGARSModulation;
  }
}
