// This file was generated by the TNO Bean Generator.
// Any modifications to this file will be lost upon re-generation.
// Generated on: 2020/03/27 12:19:05

package nl.tno.rpr.datatypes;

/** Life form state */
public enum StanceCodeEnum32 {
  NotApplicable(0),
  UprightStandingStill(1),
  UprightWalking(2),
  UprightRunning(3),
  Kneeling(4),
  Prone(5),
  Crawling(6),
  Swimming(7),
  Parachuting(8),
  Jumping(9),
  Sitting(10),
  Squatting(11),
  Crouching(12),
  Wading(13),
  Surrender(14),
  Detained(15);

  private final int value;

  private StanceCodeEnum32(int value) {
    this.value = value;
  }

  public int getValue() {
    return value;
  }
}
