// This file was generated by the TNO Bean Generator.
// Any modifications to this file will be lost upon re-generation.
// Generated on: 2020/03/27 12:19:05

package nl.tno.rpr.datatypes;

/** Represents a single supply type and the quantity being offered or requested. */
public class SupplyStruct {

  /** The type of supply being offered or requested. */
  EntityTypeStruct SupplyType;

  /**
   * The number of units of the supply type. The unit measure depends on the supply type and shall
   * use the SI units of measurement used for such supplies.
   */
  float Quantity;

  public EntityTypeStruct getSupplyType() {
    return this.SupplyType;
  }

  public void setSupplyType(EntityTypeStruct SupplyType) {
    this.SupplyType = SupplyType;
  }

  public float getQuantity() {
    return this.Quantity;
  }

  public void setQuantity(float Quantity) {
    this.Quantity = Quantity;
  }
}
