// This file was generated by the TNO Bean Generator.
// Any modifications to this file will be lost upon re-generation.
// Generated on: 2020/03/27 12:19:05

package nl.tno.rpr.datatypes;

/** The type of tactical data link used to transmit a signal */
public enum TacticalDataLinkTypeEnum16 {
  Other((short) 0),
  PADIL((short) 1),
  NATOLink__1((short) 2),
  ATDL__1((short) 3),
  Link11B_TADILB_((short) 4),
  SituationalAwarenessDataLink_SADL_((short) 5),
  Link16LegacyFormat_JTIDS_TADIL__J_((short) 6),
  Link16LegacyFormat_JTIDS_FDL_TADIL__J_((short) 7),
  Link11A_TADILA_((short) 8),
  IJMS((short) 9),
  Link4A_TADILC_((short) 10),
  Link4C((short) 11),
  TIBS((short) 12),
  ATL((short) 13),
  ConstantSource((short) 14),
  Abbreviated_Command_and_Control((short) 15),
  MILSTAR((short) 16),
  ATHS((short) 17),
  OTHGOLD((short) 18),
  TACELINT((short) 19),
  WeaponsDataLink_AWW__13_((short) 20),
  AbbreviatedCommandAndControl((short) 21),
  EnhancedPositionLocationReportingSystem_EPLRS_((short) 22),
  PositionLocationReportingSystem_PLRS_((short) 23),
  SINCGARS((short) 24),
  HaveQuickI((short) 25),
  HaveQuickII((short) 26),
  HaveQuickIIA_Saturn_((short) 27),
  Intra__FlightDataLink1((short) 28),
  Intra__FlightDataLink2((short) 29),
  ImprovedDataModem_IDM_((short) 30),
  AirForceApplicationProgramDevelopment_AFAPD_((short) 31),
  CooperativeEngagementCapability_CEC_((short) 32),
  ForwardAreaAirDefense_FAAD_DataLink_FDL_((short) 33),
  GroundBasedDataLink_GBDL_((short) 34),
  IntraVehicularInfoSystem_IVIS_((short) 35),
  MarineTacticalSystem_MTS_((short) 36),
  TacticalFireDirectionSystem_TACFIRE_((short) 37),
  IntegratedBroadcastService_IBS_((short) 38),
  AirborneInformationTransfer_ABIT_((short) 39),
  AdvancedTacticalAirborneReconnaissanceSystem_ATARS_DataLink((short) 40),
  BattleGroupPassiveHorizonExtensionSystem_BGPHES_DataLink((short) 41),
  CommonHighBandwidthDataLink_CHBDL_((short) 42),
  GuardrailInteroperableDataLink_IDL_((short) 43),
  GuardrailCommonSensorSystemOne_CSS1_DataLink((short) 44),
  GuardrailCommonSensorSystemTwo_CSS2_DataLink((short) 45),
  GuardrailCSS2Multi__RoleDataLink_MRDL_((short) 46),
  GuardrailCSS2DirectAirToSatelliteRelay_DASR_DataLink((short) 47),
  LineOfSight_LOS_DataLinkImplementation_LOSTether_((short) 48),
  LightweightCDL_LWCDL_((short) 49),
  L__52M_SR__71_((short) 50),
  RivetReach_RivetOwlDataLink((short) 51),
  SeniorSpan((short) 52),
  SeniorSpur((short) 53),
  SeniorStretch_((short) 54),
  SeniorYearInteroperableDataLink_IDL_((short) 55),
  SpaceCDL((short) 56),
  TR__1ModeMISTAirborneDataLink((short) 57),
  Ku__bandSATCOMDataLinkImplementation_UAV_((short) 58),
  MissionEquipmentControlDataLink_MECDL_((short) 59),
  RadarDataTransmittingSetDataLink((short) 60),
  SurveillanceAndControlDataLink_SCDL_((short) 61),
  TacticalUAVVideo((short) 62),
  UHFSATCOMDataLinkImplementation_UAV_((short) 63),
  TacticalCommonDataLink_TCDL_((short) 64),
  LowLevelAirPictureInterface_LLAPI_((short) 65),
  WeaponsDataLink_AGM__130_((short) 66),
  AutomaticIdentificationSystem_AIS_((short) 67),
  WeaponsDataLink_AIM__120_((short) 68),
  GC3((short) 99),
  Link16StandardizedFormat_JTIDS_MIDS_TADILJ_((short) 100),
  Link16EnhancedDataRate_EDRJTIDS_MIDS_TADIL__J_((short) 101),
  JTIDS_MIDSNetDataLoad_TIMS_TOMS_((short) 102),
  Link22((short) 103),
  AFIWCIADSCommunicationsLinks((short) 104),
  F__22Intra__FlightDataLink_IFDL_((short) 105),
  L__BandSATCOM((short) 106),
  TSAFCommunicationsLink((short) 107),
  EnhancedSINCGARS7_3((short) 108),
  F__35MultifunctionAdvancedDataLink_MADL_((short) 109),
  CursorOnTarget((short) 110);

  private final short value;

  private TacticalDataLinkTypeEnum16(short value) {
    this.value = value;
  }

  public short getValue() {
    return value;
  }
}
