// This file was generated by the TNO Bean Generator.
// Any modifications to this file will be lost upon re-generation.
// Generated on: 2020/03/27 12:19:05

package nl.tno.rpr.datatypes;

/** The current operational state of a radio transmitter. */
public enum TransmitterOperationalStatusEnum8 {
  Off((byte) 0),
  OnButNotTransmitting((byte) 1),
  OnAndTransmitting((byte) 2);

  private final byte value;

  private TransmitterOperationalStatusEnum8(byte value) {
    this.value = value;
  }

  public byte getValue() {
    return value;
  }
}
