// This file was generated by the TNO Bean Generator.
// Any modifications to this file will be lost upon re-generation.
// Generated on: 2020/03/27 12:19:05

package nl.tno.rpr.datatypes;

/** Detailed modulation types for an unmodulated carrier */
public enum UnmodulatedTypeEnum16 {
  Other((short) 0),
  ContinuousWaveEmission((short) 1);

  private final short value;

  private UnmodulatedTypeEnum16(short value) {
    this.value = value;
  }

  public short getValue() {
    return value;
  }
}
