// This file was generated by the TNO Bean Generator.
// Any modifications to this file will be lost upon re-generation.
// Generated on: 2020/03/27 12:19:05

package nl.tno.rpr.datatypes;

/** The ID of the user protocol used to transmit a radio signal. */
public enum UserProtocolEnum32 {
  CCSIL(1),
  A2ATD_SINCGARS_ERF(5),
  A2ATD_CAC2(6),
  Battle_Command(20),
  AFIWCIADSTrackReport(30),
  AFIWCIADSCommC2Message(31),
  AFIWCIADSGroundControlInterceptor_GCI_Command(32),
  AFIWCVoiceTextMessage(35),
  ModSAF_Text_Radio(177),
  CCTT_SINCGARS_ERF__LOCKOUT(200),
  CCTT_SINCGARS_ERF__HOPSET(201),
  CCTT_SINCGARS_OTAR(202),
  CCTT_SINCGARS_DATA(203),
  ModSAF_FWA_Forward_Air_Controller(546),
  ModSAF_Threat_ADA_C3(832),
  F__16_MTC_AFAPD(1000),
  F__16_MTC_IDL(1100),
  AutomaticIdentificationSystem_AIS_(1371),
  ModSAF_Artillery_Fire_Control(4570),
  AGTS(5361),
  GC3(6000),
  WNCP_data(6010),
  Spoken_text_message(6020),
  Longbow_IDM_message(6661),
  Comanche_IDM_message(6662),
  Longbow_Airborne_TACFIRE_Message(6663),
  Longbow_Ground_TACFIRE_Message(6664),
  LongbowAFAPDMessage(6665),
  Longbow_ERF_message(6666);

  private final int value;

  private UserProtocolEnum32(int value) {
    this.value = value;
  }

  public int getValue() {
    return value;
  }
}
