// This file was generated by the TNO Bean Generator.
// Any modifications to this file will be lost upon re-generation.
// Generated on: 2020/03/27 12:19:05

package nl.tno.rpr.datatypes;

/** Operational data for describing the vectoring nozzle systems being simulated. */
public class VectoringNozzleSystemDataStruct {

  /** The nozzle deflection angle in the horizontal body axis of the entity. */
  float HorizontalDeflectionAngle;

  /** The nozzle deflection angle in the vertical body axis of the entity. */
  float VerticalDeflectionAngle;

  public float getHorizontalDeflectionAngle() {
    return this.HorizontalDeflectionAngle;
  }

  public void setHorizontalDeflectionAngle(float HorizontalDeflectionAngle) {
    this.HorizontalDeflectionAngle = HorizontalDeflectionAngle;
  }

  public float getVerticalDeflectionAngle() {
    return this.VerticalDeflectionAngle;
  }

  public void setVerticalDeflectionAngle(float VerticalDeflectionAngle) {
    this.VerticalDeflectionAngle = VerticalDeflectionAngle;
  }
}
