// This file was generated by the TNO Bean Generator.
// Any modifications to this file will be lost upon re-generation.
// Generated on: 2020/03/27 12:19:05

package nl.tno.rpr.datatypes;

/** The rate at which the position is changing over time. */
public class VelocityVectorStruct {

  /** Velocity component along the X axis. */
  float XVelocity;

  /** Velocity component along the Y axis. */
  float YVelocity;

  /** Velocity component along the Z axis. */
  float ZVelocity;

  public float getXVelocity() {
    return this.XVelocity;
  }

  public void setXVelocity(float XVelocity) {
    this.XVelocity = XVelocity;
  }

  public float getYVelocity() {
    return this.YVelocity;
  }

  public void setYVelocity(float YVelocity) {
    this.YVelocity = YVelocity;
  }

  public float getZVelocity() {
    return this.ZVelocity;
  }

  public void setZVelocity(float ZVelocity) {
    this.ZVelocity = ZVelocity;
  }
}
