// This file was generated by the TNO Bean Generator.
// Any modifications to this file will be lost upon re-generation.
// Generated on: 2020/03/27 12:19:05

package nl.tno.rpr.datatypes;

/** Minefield lane marker visible side */
public enum VisibleSideLocationEnum32 {
  LeftSideVisible(0),
  RightSideVisible(1),
  BothSideVisible(2);

  private final int value;

  private VisibleSideLocationEnum32(int value) {
    this.value = value;
  }

  public int getValue() {
    return value;
  }
}
