// This file was generated by the TNO Bean Generator.
// Any modifications to this file will be lost upon re-generation.
// Generated on: 2020/03/27 12:19:05

package nl.tno.rpr.datatypes;

/** Weapon position */
public enum WeaponStateEnum32 {
  NoWeapon(0),
  Stowed(1),
  Deployed(2),
  FiringPosition(3);

  private final int value;

  private WeaponStateEnum32(int value) {
    this.value = value;
  }

  public int getValue() {
    return value;
  }
}
