FROM hlacontainers/lrc:portico-nightly-2016.05.28-alpine

ARG version

ADD ./build/distributions/TestApp-${version}.tar /root/application/

ADD ./docker/start.sh /root/application/start.sh

RUN ln -s /root/application/TestApp-${version} /root/application/TestApp

RUN chmod a+x /root/application/start.sh

ENV LRC_ENTRYPOINT=/root/application/start.sh
