@echo off

set IVCTFOLDER=C:\Projects\IVCT
set IVCTFOLDERWITHSLASHES=%IVCTFOLDER:\=/%
set TSBASEDIR=%IVCTFOLDER%\TS_Designator_Base
set TSNAME=TS_Designator
set TSVERSION=1.0.0
set TSDIR=%TSBASEDIR%\%TSNAME%
set TESTAPPNAME=TestApp