// This file was generated by the TNO Bean Generator.
// Any modifications to this file will be lost upon re-generation.
// Generated on: 2020/03/27 12:19:05

package nl.tno.rpr.objects;

import nl.tno.rpr.datatypes.ActiveSonarEnum16;
import nl.tno.rpr.datatypes.ActiveSonarFunctionCodeEnum8;

/** Describes the state of an active sonar system. */
public class ActiveSonar extends UnderwaterAcousticsEmission {

  /** Defines the type of sonar being represented. */
  ActiveSonarEnum16 AcousticName;

  /**
   * Declares the current primary use of the sonar. It may be used by simulatons to infer intent.
   */
  ActiveSonarFunctionCodeEnum8 FunctionCode;

  /** Unique identifier for the sonar on an entity, Starts with 1 */
  byte AcousticsIdentifier;

  public ActiveSonarEnum16 getAcousticName() {
    return this.AcousticName;
  }

  public void setAcousticName(ActiveSonarEnum16 AcousticName) {
    this.AcousticName = AcousticName;
  }

  public ActiveSonarFunctionCodeEnum8 getFunctionCode() {
    return this.FunctionCode;
  }

  public void setFunctionCode(ActiveSonarFunctionCodeEnum8 FunctionCode) {
    this.FunctionCode = FunctionCode;
  }

  public byte getAcousticsIdentifier() {
    return this.AcousticsIdentifier;
  }

  public void setAcousticsIdentifier(byte AcousticsIdentifier) {
    this.AcousticsIdentifier = AcousticsIdentifier;
  }
}
