// This file was generated by the TNO Bean Generator.
// Any modifications to this file will be lost upon re-generation.
// Generated on: 2020/03/27 12:19:05

package nl.tno.rpr.objects;

import nl.tno.rpr.datatypes.RPRboolean;

/**
 * Describes the steady state components of non-propulsion passive emissions such as those held in
 * the Additional Narrowband Database (ANDB).
 */
public class AdditionalPassiveActivities extends UnderwaterAcousticsEmission {

  /** Database index used to indicate the passive signature of the entity */
  short ActivityCode;

  /** The current state of this activity. */
  short ActivityParameter;

  /** Used to silence an additional passive activity without destroying this object. */
  RPRboolean IsSilent;

  public short getActivityCode() {
    return this.ActivityCode;
  }

  public void setActivityCode(short ActivityCode) {
    this.ActivityCode = ActivityCode;
  }

  public short getActivityParameter() {
    return this.ActivityParameter;
  }

  public void setActivityParameter(short ActivityParameter) {
    this.ActivityParameter = ActivityParameter;
  }

  public RPRboolean getIsSilent() {
    return this.IsSilent;
  }

  public void setIsSilent(RPRboolean IsSilent) {
    this.IsSilent = IsSilent;
  }
}
