// This file was generated by the TNO Bean Generator.
// Any modifications to this file will be lost upon re-generation.
// Generated on: 2020/03/27 12:19:05

package nl.tno.rpr.objects;

import nl.tno.rpr.datatypes.AggregateMarkingStruct;
import nl.tno.rpr.datatypes.AggregateStateEnum8;
import nl.tno.rpr.datatypes.DimensionStruct;
import nl.tno.rpr.datatypes.ForceIdentifierEnum8;
import nl.tno.rpr.datatypes.FormationEnum32;
import nl.tno.rpr.datatypes.SilentAggregateStruct;
import nl.tno.rpr.datatypes.SilentEntityStruct;
import nl.tno.rpr.datatypes.VariableDatumStruct;

/**
 * A group of one or more separate objects that operate together as part of an organization. These
 * objects may be discrete, may be other aggregate objects, or may be a mixture of both.
 */
public class AggregateEntity extends BaseEntity {

  /**
   * A unique marking or combination of characters used to distinguish the aggregate from other
   * aggregates.
   */
  AggregateMarkingStruct AggregateMarking;

  /** An indicator of the extent of association of objects form an operating group. */
  AggregateStateEnum8 AggregateState;

  /** The size of the area covered by the units in the aggregate. */
  DimensionStruct Dimensions;

  /** The identification of entities that are contained within the aggregate. */
  String[] EntityIdentifiers;

  /** The identification of the force that the aggregate belongs to. */
  ForceIdentifierEnum8 ForceIdentifier;

  /** The category of positional arrangement of the entities within the aggregate. */
  FormationEnum32 Formation;

  /** The number of elements in the SilentEntities list. */
  short NumberOfSilentEntities;

  /** The number of records in the VariableDatums structure. */
  int NumberOfVariableDatums;

  /**
   * The numbers and types, of silent aggregates contained in the aggregate. Silent aggregates are
   * sub-aggregates that are in the aggregate, but that are not separately represented in the
   * virtual world.
   */
  SilentAggregateStruct[] SilentAggregates;

  /**
   * The numbers and types, of silent entities in the aggregate. Silent entities are entities that
   * are in the aggregate, but that are not separately represented in the virtual world.
   */
  SilentEntityStruct[] SilentEntities;

  /**
   * The identifications of aggregates represented in the virtual world that are contained in the
   * aggregate.
   */
  String[] SubAggregateIdentifiers;

  /** Extra data that describes the aggregate. */
  VariableDatumStruct[] VariableDatums;

  public AggregateMarkingStruct getAggregateMarking() {
    return this.AggregateMarking;
  }

  public void setAggregateMarking(AggregateMarkingStruct AggregateMarking) {
    this.AggregateMarking = AggregateMarking;
  }

  public AggregateStateEnum8 getAggregateState() {
    return this.AggregateState;
  }

  public void setAggregateState(AggregateStateEnum8 AggregateState) {
    this.AggregateState = AggregateState;
  }

  public DimensionStruct getDimensions() {
    return this.Dimensions;
  }

  public void setDimensions(DimensionStruct Dimensions) {
    this.Dimensions = Dimensions;
  }

  public String[] getEntityIdentifiers() {
    return this.EntityIdentifiers;
  }

  public void setEntityIdentifiers(String[] EntityIdentifiers) {
    this.EntityIdentifiers = EntityIdentifiers;
  }

  public ForceIdentifierEnum8 getForceIdentifier() {
    return this.ForceIdentifier;
  }

  public void setForceIdentifier(ForceIdentifierEnum8 ForceIdentifier) {
    this.ForceIdentifier = ForceIdentifier;
  }

  public FormationEnum32 getFormation() {
    return this.Formation;
  }

  public void setFormation(FormationEnum32 Formation) {
    this.Formation = Formation;
  }

  public short getNumberOfSilentEntities() {
    return this.NumberOfSilentEntities;
  }

  public void setNumberOfSilentEntities(short NumberOfSilentEntities) {
    this.NumberOfSilentEntities = NumberOfSilentEntities;
  }

  public int getNumberOfVariableDatums() {
    return this.NumberOfVariableDatums;
  }

  public void setNumberOfVariableDatums(int NumberOfVariableDatums) {
    this.NumberOfVariableDatums = NumberOfVariableDatums;
  }

  public SilentAggregateStruct[] getSilentAggregates() {
    return this.SilentAggregates;
  }

  public void setSilentAggregates(SilentAggregateStruct[] SilentAggregates) {
    this.SilentAggregates = SilentAggregates;
  }

  public SilentEntityStruct[] getSilentEntities() {
    return this.SilentEntities;
  }

  public void setSilentEntities(SilentEntityStruct[] SilentEntities) {
    this.SilentEntities = SilentEntities;
  }

  public String[] getSubAggregateIdentifiers() {
    return this.SubAggregateIdentifiers;
  }

  public void setSubAggregateIdentifiers(String[] SubAggregateIdentifiers) {
    this.SubAggregateIdentifiers = SubAggregateIdentifiers;
  }

  public VariableDatumStruct[] getVariableDatums() {
    return this.VariableDatums;
  }

  public void setVariableDatums(VariableDatumStruct[] VariableDatums) {
    this.VariableDatums = VariableDatums;
  }
}
