// This file was generated by the TNO Bean Generator.
// Any modifications to this file will be lost upon re-generation.
// Generated on: 2020/03/27 12:19:05

package nl.tno.rpr.objects;

/**
 * A platform entity that operates mainly in the air, such as aircraft, balloons, etc. This includes
 * the entities when they are on the ground.
 */
public class Aircraft extends Platform {}
