// This file was generated by the TNO Bean Generator.
// Any modifications to this file will be lost upon re-generation.
// Generated on: 2020/03/27 12:19:05

package nl.tno.rpr.objects;

import nl.tno.rpr.datatypes.BreachStruct;

/** A breach linear object. */
public class BreachObject extends LinearObject {

  /** Specifies a breach linear object */
  BreachStruct[] SegmentRecords;

  public BreachStruct[] getSegmentRecords() {
    return this.SegmentRecords;
  }

  public void setSegmentRecords(BreachStruct[] SegmentRecords) {
    this.SegmentRecords = SegmentRecords;
  }
}
