// This file was generated by the TNO Bean Generator.
// Any modifications to this file will be lost upon re-generation.
// Generated on: 2020/03/27 12:19:05

package nl.tno.rpr.objects;

import nl.tno.rpr.datatypes.BreachedStatusEnum8;

/** A point object that can be breached. */
public class BreachablePointObject extends PointObject {

  /** Specifies the breached appearance of the object */
  BreachedStatusEnum8 BreachedStatus;

  public BreachedStatusEnum8 getBreachedStatus() {
    return this.BreachedStatus;
  }

  public void setBreachedStatus(BreachedStatusEnum8 BreachedStatus) {
    this.BreachedStatus = BreachedStatus;
  }
}
