// This file was generated by the TNO Bean Generator.
// Any modifications to this file will be lost upon re-generation.
// Generated on: 2020/03/27 12:19:05

package nl.tno.rpr.objects;

/**
 * A pit, depression, or cavity formed in the surface of the earth by an explosion. The depression's
 * shape can range from saucer to conical, depending largely of the depth of burst.
 */
public class CraterObject extends PointObject {

  /**
   * Specifies the diameter of the crater, where the center of the crater is at the point object
   * location
   */
  int CraterSize;

  public int getCraterSize() {
    return this.CraterSize;
  }

  public void setCraterSize(int CraterSize) {
    this.CraterSize = CraterSize;
  }
}
