// This file was generated by the TNO Bean Generator.
// Any modifications to this file will be lost upon re-generation.
// Generated on: 2020/03/27 12:19:05

package nl.tno.rpr.objects;

import nl.tno.rpr.datatypes.RPRboolean;

/** Engineering and natural effects such as craters, bridges, vehicle tracks, etc. */
public class CulturalFeature extends PhysicalEntity {

  /** Whether the cultural feature's external lights are on or not. */
  RPRboolean ExternalLightsOn;

  /** Whether the cultural feature's internal heat source is on or not. */
  RPRboolean InternalHeatSourceOn;

  /** Whether the cultural feature's internal lights are on or not. */
  RPRboolean InternalLightsOn;

  public RPRboolean getExternalLightsOn() {
    return this.ExternalLightsOn;
  }

  public void setExternalLightsOn(RPRboolean ExternalLightsOn) {
    this.ExternalLightsOn = ExternalLightsOn;
  }

  public RPRboolean getInternalHeatSourceOn() {
    return this.InternalHeatSourceOn;
  }

  public void setInternalHeatSourceOn(RPRboolean InternalHeatSourceOn) {
    this.InternalHeatSourceOn = InternalHeatSourceOn;
  }

  public RPRboolean getInternalLightsOn() {
    return this.InternalLightsOn;
  }

  public void setInternalLightsOn(RPRboolean InternalLightsOn) {
    this.InternalLightsOn = InternalLightsOn;
  }
}
