// This file was generated by the TNO Bean Generator.
// Any modifications to this file will be lost upon re-generation.
// Generated on: 2020/03/27 12:19:05

package nl.tno.rpr.objects;

/**
 * Countermeasures devices that are dispensed from another entity. The devices may be active
 * emitters or passive reflectors of energy.
 */
public class Expendables extends PhysicalEntity {}
