// This file was generated by the TNO Bean Generator.
// Any modifications to this file will be lost upon re-generation.
// Generated on: 2020/03/27 12:19:05

package nl.tno.rpr.objects;

import nl.tno.rpr.datatypes.RPRboolean;

/**
 * An emitter beam that is designed to jam or otherwise interfere or confuse another emitter system
 */
public class JammerBeam extends EmitterBeam {

  /** The jamming mode technique or series of techniques being applied. */
  int JammingModeSequence;

  /** Identification of the emitter beams being jammed. */
  String[] JammedObjectIdentifiers;

  /**
   * When TRUE the receiving simulation can assume that all emitter beams that are in the scan
   * pattern of the jammer beam are being jammed
   */
  RPRboolean HighDensityJam;

  public int getJammingModeSequence() {
    return this.JammingModeSequence;
  }

  public void setJammingModeSequence(int JammingModeSequence) {
    this.JammingModeSequence = JammingModeSequence;
  }

  public String[] getJammedObjectIdentifiers() {
    return this.JammedObjectIdentifiers;
  }

  public void setJammedObjectIdentifiers(String[] JammedObjectIdentifiers) {
    this.JammedObjectIdentifiers = JammedObjectIdentifiers;
  }

  public RPRboolean getHighDensityJam() {
    return this.HighDensityJam;
  }

  public void setHighDensityJam(RPRboolean HighDensityJam) {
    this.HighDensityJam = HighDensityJam;
  }
}
