// This file was generated by the TNO Bean Generator.
// Any modifications to this file will be lost upon re-generation.
// Generated on: 2020/03/27 12:19:05

package nl.tno.rpr.objects;

/**
 * A synthetic environment object that has size and an orientation and is geometrically anchored to
 * the terrain with one point.
 */
public class LinearObject extends EnvironmentObject {}
