// This file was generated by the TNO Bean Generator.
// Any modifications to this file will be lost upon re-generation.
// Generated on: 2020/03/27 12:19:05

package nl.tno.rpr.objects;

import nl.tno.rpr.datatypes.RPRboolean;

/**
 * A complete device charged with explosives, propellants, pyrotechnics, initiating composition, or
 * nuclear, biological or chemical material for use in military operations, including demolitions.
 */
public class Munition extends PhysicalEntity {

  /** Whether the flash of the munition being launched is present or not. */
  RPRboolean LauncherFlashPresent;

  public RPRboolean getLauncherFlashPresent() {
    return this.LauncherFlashPresent;
  }

  public void setLauncherFlashPresent(RPRboolean LauncherFlashPresent) {
    this.LauncherFlashPresent = LauncherFlashPresent;
  }
}
