// This file was generated by the TNO Bean Generator.
// Any modifications to this file will be lost upon re-generation.
// Generated on: 2020/03/27 12:19:05

package nl.tno.rpr.objects;

/** The part of an IFF system that first transmits electromagnetic signals. */
public class NatoIFFInterrogator extends NatoIFF {}
