// This file was generated by the TNO Bean Generator.
// Any modifications to this file will be lost upon re-generation.
// Generated on: 2020/03/27 12:19:05

package nl.tno.rpr.objects;

import nl.tno.rpr.datatypes.RPRboolean;

/**
 * The part of a specific IFF system that responds (for example by emitting pulses) to the
 * electromagnetic signals.
 */
public class NatoIFFTransponder extends NatoIFF {

  /** Specifies whether or not emergency is on. */
  RPRboolean EmergencyOn;

  /** Specifies whether or not the squawk ident/flash is on. */
  RPRboolean IdentSquawkFlashOn;

  /** Mode 1 code, two octal values. */
  short Mode1Code;

  /** Mode 2 code, four octal values. */
  short Mode2Code;

  /** Mode 3 code, four octal values. */
  short Mode3ACode;

  /** Parameter 5 - Mode C altitude. */
  short Mode5CAltitude;

  /** Specifies whether or not Parameter 5 - Mode C altitude is available. */
  RPRboolean Mode5CAltitudeAvailable;

  /** Specifies whether or not STI is on. */
  RPRboolean StiOn;

  public RPRboolean getEmergencyOn() {
    return this.EmergencyOn;
  }

  public void setEmergencyOn(RPRboolean EmergencyOn) {
    this.EmergencyOn = EmergencyOn;
  }

  public RPRboolean getIdentSquawkFlashOn() {
    return this.IdentSquawkFlashOn;
  }

  public void setIdentSquawkFlashOn(RPRboolean IdentSquawkFlashOn) {
    this.IdentSquawkFlashOn = IdentSquawkFlashOn;
  }

  public short getMode1Code() {
    return this.Mode1Code;
  }

  public void setMode1Code(short Mode1Code) {
    this.Mode1Code = Mode1Code;
  }

  public short getMode2Code() {
    return this.Mode2Code;
  }

  public void setMode2Code(short Mode2Code) {
    this.Mode2Code = Mode2Code;
  }

  public short getMode3ACode() {
    return this.Mode3ACode;
  }

  public void setMode3ACode(short Mode3ACode) {
    this.Mode3ACode = Mode3ACode;
  }

  public short getMode5CAltitude() {
    return this.Mode5CAltitude;
  }

  public void setMode5CAltitude(short Mode5CAltitude) {
    this.Mode5CAltitude = Mode5CAltitude;
  }

  public RPRboolean getMode5CAltitudeAvailable() {
    return this.Mode5CAltitudeAvailable;
  }

  public void setMode5CAltitudeAvailable(RPRboolean Mode5CAltitudeAvailable) {
    this.Mode5CAltitudeAvailable = Mode5CAltitudeAvailable;
  }

  public RPRboolean getStiOn() {
    return this.StiOn;
  }

  public void setStiOn(RPRboolean StiOn) {
    this.StiOn = StiOn;
  }
}
