// This file was generated by the TNO Bean Generator.
// Any modifications to this file will be lost upon re-generation.
// Generated on: 2020/03/27 12:19:05

package nl.tno.rpr.objects;

/** Areal objects other than Minefield objects. */
public class OtherArealObject extends ArealObject {}
