// This file was generated by the TNO Bean Generator.
// Any modifications to this file will be lost upon re-generation.
// Generated on: 2020/03/27 12:19:05

package nl.tno.rpr.objects;

/** A ribbon bridge object. */
public class RibbonBridgeObject extends PointObject {

  /** Specifies the number of segments composing the ribbon bridge */
  int NumberOfSegments;

  public int getNumberOfSegments() {
    return this.NumberOfSegments;
  }

  public void setNumberOfSegments(int NumberOfSegments) {
    this.NumberOfSegments = NumberOfSegments;
  }
}
