// This file was generated by the TNO Bean Generator.
// Any modifications to this file will be lost upon re-generation.
// Generated on: 2020/03/27 12:19:05

package nl.tno.rpr.objects;

/** Supplies other than munitions, such as fuel, food and personnel. */
public class Supplies extends PhysicalEntity {}
